/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2Body extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Rot B2Rot_TEMP_GEN_0;

    private B2Transform B2Transform_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    private B2Vec2 B2Vec2_TEMP_GEN_3;

    private B2Vec2 B2Vec2_TEMP_GEN_4;

    private B2Vec2 B2Vec2_TEMP_GEN_5;

    private B2Vec2 B2Vec2_TEMP_GEN_6;

    private B2Vec2 B2Vec2_TEMP_GEN_7;

    private B2MassData B2MassData_TEMP_GEN_0;

    private B2AABB B2AABB_TEMP_GEN_0;

    static public final B2Body NULL = B2Body.native_new();

    public B2Body() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Body(long bodyId) {
        long addr = internal_native_create_long_addr(bodyId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long bodyId) {
        try {
            return (long) FFMHandles.internal_native_create_long_addr__J.invokeExact(bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Body(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Body native_new() {
        return new B2Body((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsValid__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Destroy() {
        internal_native_Destroy(native_address);
    }

    public static void internal_native_Destroy(long this_addr) {
        try {
            FFMHandles.internal_native_Destroy__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetType() {
        return internal_native_GetType(native_address);
    }

    public static int internal_native_GetType(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetType__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetType(int type) {
        internal_native_SetType(native_address, type);
    }

    public static void internal_native_SetType(long this_addr, int type) {
        try {
            FFMHandles.internal_native_SetType__JI.invokeExact(this_addr, type);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetPosition() {
        long addr = internal_native_GetPosition_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetPosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetPosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Rot GetRotation() {
        long addr = internal_native_GetRotation_addr(native_address);
        if (addr == 0)
            return B2Rot.NULL;
        if (B2Rot_TEMP_GEN_0 == null)
            B2Rot_TEMP_GEN_0 = B2Rot.native_new();
        B2Rot_TEMP_GEN_0.internal_reset(addr, false);
        return B2Rot_TEMP_GEN_0;
    }

    public static long internal_native_GetRotation_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetRotation_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Transform GetTransform() {
        long addr = internal_native_GetTransform_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_0 == null)
            B2Transform_TEMP_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransform_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTransform_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTransform(B2Vec2 position, B2Rot rotation) {
        internal_native_SetTransform(native_address, position.native_address, rotation.native_address);
    }

    public static void internal_native_SetTransform(long this_addr, long position_addr, long rotation_addr) {
        try {
            FFMHandles.internal_native_SetTransform__JJJ.invokeExact(this_addr, position_addr, rotation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetTransform(B2Transform target, float timeStep) {
        internal_native_SetTargetTransform(native_address, target.native_address, timeStep);
    }

    public static void internal_native_SetTargetTransform(long this_addr, long target_addr, float timeStep) {
        try {
            FFMHandles.internal_native_SetTargetTransform__JJF.invokeExact(this_addr, target_addr, timeStep);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalPoint(B2Vec2 worldPoint) {
        long addr = internal_native_GetLocalPoint_addr(native_address, worldPoint.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalPoint_addr(long this_addr, long worldPoint_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalPoint_addr__JJ.invokeExact(this_addr, worldPoint_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetWorldPoint(B2Vec2 localPoint) {
        long addr = internal_native_GetWorldPoint_addr(native_address, localPoint.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetWorldPoint_addr(long this_addr, long localPoint_addr) {
        try {
            return (long) FFMHandles.internal_native_GetWorldPoint_addr__JJ.invokeExact(this_addr, localPoint_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalVector(B2Vec2 worldVector) {
        long addr = internal_native_GetLocalVector_addr(native_address, worldVector.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_3 == null)
            B2Vec2_TEMP_GEN_3 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_3.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_3;
    }

    public static long internal_native_GetLocalVector_addr(long this_addr, long worldVector_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalVector_addr__JJ.invokeExact(this_addr, worldVector_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetWorldVector(B2Vec2 localVector) {
        long addr = internal_native_GetWorldVector_addr(native_address, localVector.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_4 == null)
            B2Vec2_TEMP_GEN_4 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_4.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_4;
    }

    public static long internal_native_GetWorldVector_addr(long this_addr, long localVector_addr) {
        try {
            return (long) FFMHandles.internal_native_GetWorldVector_addr__JJ.invokeExact(this_addr, localVector_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLinearVelocity() {
        long addr = internal_native_GetLinearVelocity_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_5 == null)
            B2Vec2_TEMP_GEN_5 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_5.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_5;
    }

    public static long internal_native_GetLinearVelocity_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLinearVelocity_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLinearVelocity(B2Vec2 velocity) {
        internal_native_SetLinearVelocity(native_address, velocity.native_address);
    }

    public static void internal_native_SetLinearVelocity(long this_addr, long velocity_addr) {
        try {
            FFMHandles.internal_native_SetLinearVelocity__JJ.invokeExact(this_addr, velocity_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetAngularVelocity() {
        return internal_native_GetAngularVelocity(native_address);
    }

    public static float internal_native_GetAngularVelocity(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetAngularVelocity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetAngularVelocity(float velocity) {
        internal_native_SetAngularVelocity(native_address, velocity);
    }

    public static void internal_native_SetAngularVelocity(long this_addr, float velocity) {
        try {
            FFMHandles.internal_native_SetAngularVelocity__JF.invokeExact(this_addr, velocity);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyForce(B2Vec2 force, B2Vec2 point, boolean wake) {
        internal_native_ApplyForce(native_address, force.native_address, point.native_address, wake);
    }

    public static void internal_native_ApplyForce(long this_addr, long force_addr, long point_addr, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyForce__JJJZ.invokeExact(this_addr, force_addr, point_addr, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyForceToCenter(B2Vec2 force, boolean wake) {
        internal_native_ApplyForceToCenter(native_address, force.native_address, wake);
    }

    public static void internal_native_ApplyForceToCenter(long this_addr, long force_addr, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyForceToCenter__JJZ.invokeExact(this_addr, force_addr, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyTorque(float torque, boolean wake) {
        internal_native_ApplyTorque(native_address, torque, wake);
    }

    public static void internal_native_ApplyTorque(long this_addr, float torque, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyTorque__JFZ.invokeExact(this_addr, torque, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyLinearImpulse(B2Vec2 impulse, B2Vec2 point, boolean wake) {
        internal_native_ApplyLinearImpulse(native_address, impulse.native_address, point.native_address, wake);
    }

    public static void internal_native_ApplyLinearImpulse(long this_addr, long impulse_addr, long point_addr, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyLinearImpulse__JJJZ.invokeExact(this_addr, impulse_addr, point_addr, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyLinearImpulseToCenter(B2Vec2 impulse, boolean wake) {
        internal_native_ApplyLinearImpulseToCenter(native_address, impulse.native_address, wake);
    }

    public static void internal_native_ApplyLinearImpulseToCenter(long this_addr, long impulse_addr, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyLinearImpulseToCenter__JJZ.invokeExact(this_addr, impulse_addr, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyAngularImpulse(float impulse, boolean wake) {
        internal_native_ApplyAngularImpulse(native_address, impulse, wake);
    }

    public static void internal_native_ApplyAngularImpulse(long this_addr, float impulse, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyAngularImpulse__JFZ.invokeExact(this_addr, impulse, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMass() {
        return internal_native_GetMass(native_address);
    }

    public static float internal_native_GetMass(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMass__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetRotationalInertia() {
        return internal_native_GetRotationalInertia(native_address);
    }

    public static float internal_native_GetRotationalInertia(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetRotationalInertia__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalCenterOfMass() {
        long addr = internal_native_GetLocalCenterOfMass_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_6 == null)
            B2Vec2_TEMP_GEN_6 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_6.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_6;
    }

    public static long internal_native_GetLocalCenterOfMass_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalCenterOfMass_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetWorldCenterOfMass() {
        long addr = internal_native_GetWorldCenterOfMass_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_7 == null)
            B2Vec2_TEMP_GEN_7 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_7.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_7;
    }

    public static long internal_native_GetWorldCenterOfMass_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetWorldCenterOfMass_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2MassData GetMassData() {
        long addr = internal_native_GetMassData_addr(native_address);
        if (addr == 0)
            return B2MassData.NULL;
        if (B2MassData_TEMP_GEN_0 == null)
            B2MassData_TEMP_GEN_0 = B2MassData.native_new();
        B2MassData_TEMP_GEN_0.internal_reset(addr, false);
        return B2MassData_TEMP_GEN_0;
    }

    public static long internal_native_GetMassData_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetMassData_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMassData(B2MassData massData) {
        internal_native_SetMassData(native_address, massData.native_address);
    }

    public static void internal_native_SetMassData(long this_addr, long massData_addr) {
        try {
            FFMHandles.internal_native_SetMassData__JJ.invokeExact(this_addr, massData_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyMassFromShapes() {
        internal_native_ApplyMassFromShapes(native_address);
    }

    public static void internal_native_ApplyMassFromShapes(long this_addr) {
        try {
            FFMHandles.internal_native_ApplyMassFromShapes__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLinearDamping() {
        return internal_native_GetLinearDamping(native_address);
    }

    public static float internal_native_GetLinearDamping(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLinearDamping__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLinearDamping(float damping) {
        internal_native_SetLinearDamping(native_address, damping);
    }

    public static void internal_native_SetLinearDamping(long this_addr, float damping) {
        try {
            FFMHandles.internal_native_SetLinearDamping__JF.invokeExact(this_addr, damping);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetAngularDamping() {
        return internal_native_GetAngularDamping(native_address);
    }

    public static float internal_native_GetAngularDamping(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetAngularDamping__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetAngularDamping(float damping) {
        internal_native_SetAngularDamping(native_address, damping);
    }

    public static void internal_native_SetAngularDamping(long this_addr, float damping) {
        try {
            FFMHandles.internal_native_SetAngularDamping__JF.invokeExact(this_addr, damping);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetGravityScale() {
        return internal_native_GetGravityScale(native_address);
    }

    public static float internal_native_GetGravityScale(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetGravityScale__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetGravityScale(float scale) {
        internal_native_SetGravityScale(native_address, scale);
    }

    public static void internal_native_SetGravityScale(long this_addr, float scale) {
        try {
            FFMHandles.internal_native_SetGravityScale__JF.invokeExact(this_addr, scale);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsAwake() {
        return internal_native_IsAwake(native_address);
    }

    public static boolean internal_native_IsAwake(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsAwake__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetAwake(boolean awake) {
        internal_native_SetAwake(native_address, awake);
    }

    public static void internal_native_SetAwake(long this_addr, boolean awake) {
        try {
            FFMHandles.internal_native_SetAwake__JZ.invokeExact(this_addr, awake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsSleepEnabled() {
        return internal_native_IsSleepEnabled(native_address);
    }

    public static boolean internal_native_IsSleepEnabled(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsSleepEnabled__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void EnableSleep(boolean enabled) {
        internal_native_EnableSleep(native_address, enabled);
    }

    public static void internal_native_EnableSleep(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_EnableSleep__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsEnabled() {
        return internal_native_IsEnabled(native_address);
    }

    public static boolean internal_native_IsEnabled(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsEnabled__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Disable() {
        internal_native_Disable(native_address);
    }

    public static void internal_native_Disable(long this_addr) {
        try {
            FFMHandles.internal_native_Disable__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Enable() {
        internal_native_Enable(native_address);
    }

    public static void internal_native_Enable(long this_addr) {
        try {
            FFMHandles.internal_native_Enable__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsFixedRotation() {
        return internal_native_IsFixedRotation(native_address);
    }

    public static boolean internal_native_IsFixedRotation(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsFixedRotation__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetFixedRotation(boolean fixedRotation) {
        internal_native_SetFixedRotation(native_address, fixedRotation);
    }

    public static void internal_native_SetFixedRotation(long this_addr, boolean fixedRotation) {
        try {
            FFMHandles.internal_native_SetFixedRotation__JZ.invokeExact(this_addr, fixedRotation);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsBullet() {
        return internal_native_IsBullet(native_address);
    }

    public static boolean internal_native_IsBullet(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsBullet__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBullet(boolean bullet) {
        internal_native_SetBullet(native_address, bullet);
    }

    public static void internal_native_SetBullet(long this_addr, boolean bullet) {
        try {
            FFMHandles.internal_native_SetBullet__JZ.invokeExact(this_addr, bullet);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetShapeCount() {
        return internal_native_GetShapeCount(native_address);
    }

    public static int internal_native_GetShapeCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetShapeCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Shape GetShape(int index) {
        long addr = internal_native_GetShape_addr(native_address, index);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_GetShape_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetShape_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetJointCount() {
        return internal_native_GetJointCount(native_address);
    }

    public static int internal_native_GetJointCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetJointCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Joint GetJoint(int index) {
        long addr = internal_native_GetJoint_addr(native_address, index);
        if (addr == 0)
            return B2Joint.NULL;
        B2Joint B2Joint_NEW = B2Joint.native_new();
        B2Joint_NEW.internal_reset(addr, true);
        return B2Joint_NEW;
    }

    public static long internal_native_GetJoint_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetJoint_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2AABB ComputeAABB() {
        long addr = internal_native_ComputeAABB_addr(native_address);
        if (addr == 0)
            return B2AABB.NULL;
        if (B2AABB_TEMP_GEN_0 == null)
            B2AABB_TEMP_GEN_0 = B2AABB.native_new();
        B2AABB_TEMP_GEN_0.internal_reset(addr, false);
        return B2AABB_TEMP_GEN_0;
    }

    public static long internal_native_ComputeAABB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_ComputeAABB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Shape CreateCircleShape(B2ShapeDef def, B2Circle circle) {
        long addr = internal_native_CreateCircleShape_addr(native_address, def.native_address, circle.native_address);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_CreateCircleShape_addr(long this_addr, long def_addr, long circle_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateCircleShape_addr__JJJ.invokeExact(this_addr, def_addr, circle_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Shape CreateCapsuleShape(B2ShapeDef def, B2Capsule capsule) {
        long addr = internal_native_CreateCapsuleShape_addr(native_address, def.native_address, capsule.native_address);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_CreateCapsuleShape_addr(long this_addr, long def_addr, long capsule_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateCapsuleShape_addr__JJJ.invokeExact(this_addr, def_addr, capsule_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Shape CreateSegmentShape(B2ShapeDef def, B2Segment segment) {
        long addr = internal_native_CreateSegmentShape_addr(native_address, def.native_address, segment.native_address);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_CreateSegmentShape_addr(long this_addr, long def_addr, long segment_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateSegmentShape_addr__JJJ.invokeExact(this_addr, def_addr, segment_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Shape CreatePolygonShape(B2ShapeDef def, B2Polygon polygon) {
        long addr = internal_native_CreatePolygonShape_addr(native_address, def.native_address, polygon.native_address);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_CreatePolygonShape_addr(long this_addr, long def_addr, long polygon_addr) {
        try {
            return (long) FFMHandles.internal_native_CreatePolygonShape_addr__JJJ.invokeExact(this_addr, def_addr, polygon_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Chain CreateChain(B2ChainDef def) {
        long addr = internal_native_CreateChain_addr(native_address, def.native_address);
        if (addr == 0)
            return B2Chain.NULL;
        B2Chain B2Chain_NEW = B2Chain.native_new();
        B2Chain_NEW.internal_reset(addr, true);
        return B2Chain_NEW;
    }

    public static long internal_native_CreateChain_addr(long this_addr, long def_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateChain_addr__JJ.invokeExact(this_addr, def_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_long_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_create_long_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetId__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getid", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsValid__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_isvalid", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Destroy__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_destroy", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetType__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_gettype", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetType__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_settype", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetPosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRotation_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getrotation_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTransform_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_gettransform_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTransform__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_settransform", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetTransform__JJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_settargettransform", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalPoint_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getlocalpoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetWorldPoint_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getworldpoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalVector_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getlocalvector_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetWorldVector_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getworldvector_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLinearVelocity_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getlinearvelocity_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLinearVelocity__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setlinearvelocity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetAngularVelocity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getangularvelocity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetAngularVelocity__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setangularvelocity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_ApplyForce__JJJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applyforce", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ApplyForceToCenter__JJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applyforcetocenter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ApplyTorque__JFZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applytorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ApplyLinearImpulse__JJJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applylinearimpulse", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ApplyLinearImpulseToCenter__JJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applylinearimpulsetocenter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ApplyAngularImpulse__JFZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applyangularimpulse", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetMass__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getmass", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRotationalInertia__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getrotationalinertia", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalCenterOfMass_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getlocalcenterofmass_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetWorldCenterOfMass_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getworldcenterofmass_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMassData_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getmassdata_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMassData__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setmassdata", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ApplyMassFromShapes__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_applymassfromshapes", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLinearDamping__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getlineardamping", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLinearDamping__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setlineardamping", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetAngularDamping__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getangulardamping", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetAngularDamping__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setangulardamping", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetGravityScale__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getgravityscale", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetGravityScale__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setgravityscale", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_IsAwake__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_isawake", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetAwake__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setawake", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_IsSleepEnabled__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_issleepenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_EnableSleep__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_enablesleep", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_IsEnabled__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_isenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Disable__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_disable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Enable__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_enable", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsFixedRotation__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_isfixedrotation", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFixedRotation__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setfixedrotation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_IsBullet__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_isbullet", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBullet__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_setbullet", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetShapeCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getshapecount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetShape_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetJointCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2body_getjointcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetJoint_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_getjoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_ComputeAABB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_computeaabb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateCircleShape_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_createcircleshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateCapsuleShape_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_createcapsuleshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateSegmentShape_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_createsegmentshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreatePolygonShape_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_createpolygonshape_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateChain_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2body_createchain_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
