/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2BodyMoveEvent extends NativeObject {

    private B2Transform B2Transform_TEMP_GEN_0;

    static public final B2BodyMoveEvent NULL = B2BodyMoveEvent.native_new();

    public B2BodyMoveEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2BodyMoveEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2BodyMoveEvent native_new() {
        return new B2BodyMoveEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyId() {
        return internal_native_GetBodyId(native_address);
    }

    public static long internal_native_GetBodyId(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Transform GetTransform() {
        long addr = internal_native_GetTransform_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_0 == null)
            B2Transform_TEMP_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransform_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTransform_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetFellAsleep() {
        return internal_native_GetFellAsleep(native_address);
    }

    public static boolean internal_native_GetFellAsleep(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetFellAsleep__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2bodymoveevent_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2bodymoveevent_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyId__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2bodymoveevent_getbodyid", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTransform_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2bodymoveevent_gettransform_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetFellAsleep__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2bodymoveevent_getfellasleep", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));
    }
}
