/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2ChainDef extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2SurfaceMaterial B2SurfaceMaterial_TEMP_GEN_0;

    private B2Filter B2Filter_TEMP_GEN_0;

    static public final B2ChainDef NULL = B2ChainDef.native_new();

    public B2ChainDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ChainDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ChainDef native_new() {
        return new B2ChainDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ClearPoints() {
        internal_native_ClearPoints(native_address);
    }

    public static void internal_native_ClearPoints(long this_addr) {
        try {
            FFMHandles.internal_native_ClearPoints__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddPoint(B2Vec2 point) {
        internal_native_AddPoint(native_address, point.native_address);
    }

    public static void internal_native_AddPoint(long this_addr, long point_addr) {
        try {
            FFMHandles.internal_native_AddPoint__JJ.invokeExact(this_addr, point_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetPointCount() {
        return internal_native_GetPointCount(native_address);
    }

    public static int internal_native_GetPointCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetPointCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetPoint(int index) {
        long addr = internal_native_GetPoint_addr(native_address, index);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetPoint_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetPoint_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ClearMaterials() {
        internal_native_ClearMaterials(native_address);
    }

    public static void internal_native_ClearMaterials(long this_addr) {
        try {
            FFMHandles.internal_native_ClearMaterials__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddMaterial(B2SurfaceMaterial material) {
        internal_native_AddMaterial(native_address, material.native_address);
    }

    public static void internal_native_AddMaterial(long this_addr, long material_addr) {
        try {
            FFMHandles.internal_native_AddMaterial__JJ.invokeExact(this_addr, material_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetMaterialCount() {
        return internal_native_GetMaterialCount(native_address);
    }

    public static int internal_native_GetMaterialCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetMaterialCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2SurfaceMaterial GetMaterial(int index) {
        long addr = internal_native_GetMaterial_addr(native_address, index);
        if (addr == 0)
            return B2SurfaceMaterial.NULL;
        if (B2SurfaceMaterial_TEMP_GEN_0 == null)
            B2SurfaceMaterial_TEMP_GEN_0 = B2SurfaceMaterial.native_new();
        B2SurfaceMaterial_TEMP_GEN_0.internal_reset(addr, false);
        return B2SurfaceMaterial_TEMP_GEN_0;
    }

    public static long internal_native_GetMaterial_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetMaterial_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Filter GetFilter() {
        long addr = internal_native_GetFilter_addr(native_address);
        if (addr == 0)
            return B2Filter.NULL;
        if (B2Filter_TEMP_GEN_0 == null)
            B2Filter_TEMP_GEN_0 = B2Filter.native_new();
        B2Filter_TEMP_GEN_0.internal_reset(addr, false);
        return B2Filter_TEMP_GEN_0;
    }

    public static long internal_native_GetFilter_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetFilter_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetFilter(B2Filter filter) {
        internal_native_SetFilter(native_address, filter.native_address);
    }

    public static void internal_native_SetFilter(long this_addr, long filter_addr) {
        try {
            FFMHandles.internal_native_SetFilter__JJ.invokeExact(this_addr, filter_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetIsLoop() {
        return internal_native_GetIsLoop(native_address);
    }

    public static boolean internal_native_GetIsLoop(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetIsLoop__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetIsLoop(boolean loop) {
        internal_native_SetIsLoop(native_address, loop);
    }

    public static void internal_native_SetIsLoop(long this_addr, boolean loop) {
        try {
            FFMHandles.internal_native_SetIsLoop__JZ.invokeExact(this_addr, loop);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSensorEvents() {
        return internal_native_GetEnableSensorEvents(native_address);
    }

    public static boolean internal_native_GetEnableSensorEvents(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSensorEvents__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSensorEvents(boolean enabled) {
        internal_native_SetEnableSensorEvents(native_address, enabled);
    }

    public static void internal_native_SetEnableSensorEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSensorEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chaindef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ClearPoints__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_clearpoints", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddPoint__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_addpoint", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetPointCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_getpointcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetPoint_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chaindef_getpoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_ClearMaterials__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_clearmaterials", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddMaterial__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_addmaterial", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMaterialCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_getmaterialcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMaterial_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chaindef_getmaterial_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetFilter_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chaindef_getfilter_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFilter__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_setfilter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetIsLoop__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_getisloop", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetIsLoop__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_setisloop", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSensorEvents__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_getenablesensorevents", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSensorEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chaindef_setenablesensorevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
