/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2ChainSegment extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Segment B2Segment_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    static public final B2ChainSegment NULL = B2ChainSegment.native_new();

    public B2ChainSegment() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ChainSegment(B2Vec2 ghost1, B2Segment segment, B2Vec2 ghost2) {
        long addr = internal_native_create_B2Vec2_B2Segment_B2Vec2_addr(ghost1.native_address, segment.native_address, ghost2.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B2Vec2_B2Segment_B2Vec2_addr(long ghost1_addr, long segment_addr, long ghost2_addr) {
        try {
            return (long) FFMHandles.internal_native_create_B2Vec2_B2Segment_B2Vec2_addr__JJJ.invokeExact(ghost1_addr, segment_addr, ghost2_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ChainSegment(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ChainSegment native_new() {
        return new B2ChainSegment((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetGhost1() {
        long addr = internal_native_GetGhost1_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetGhost1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetGhost1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetGhost1(B2Vec2 point) {
        internal_native_SetGhost1(native_address, point.native_address);
    }

    public static void internal_native_SetGhost1(long this_addr, long point_addr) {
        try {
            FFMHandles.internal_native_SetGhost1__JJ.invokeExact(this_addr, point_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Segment GetSegment() {
        long addr = internal_native_GetSegment_addr(native_address);
        if (addr == 0)
            return B2Segment.NULL;
        if (B2Segment_TEMP_GEN_0 == null)
            B2Segment_TEMP_GEN_0 = B2Segment.native_new();
        B2Segment_TEMP_GEN_0.internal_reset(addr, false);
        return B2Segment_TEMP_GEN_0;
    }

    public static long internal_native_GetSegment_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetSegment_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSegment(B2Segment segment) {
        internal_native_SetSegment(native_address, segment.native_address);
    }

    public static void internal_native_SetSegment(long this_addr, long segment_addr) {
        try {
            FFMHandles.internal_native_SetSegment__JJ.invokeExact(this_addr, segment_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetGhost2() {
        long addr = internal_native_GetGhost2_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetGhost2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetGhost2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetGhost2(B2Vec2 point) {
        internal_native_SetGhost2(native_address, point.native_address);
    }

    public static void internal_native_SetGhost2(long this_addr, long point_addr) {
        try {
            FFMHandles.internal_native_SetGhost2__JJ.invokeExact(this_addr, point_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chainsegment_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_B2Vec2_B2Segment_B2Vec2_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chainsegment_create_b2vec2_b2segment_b2vec2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chainsegment_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetGhost1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chainsegment_getghost1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetGhost1__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chainsegment_setghost1", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetSegment_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chainsegment_getsegment_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSegment__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chainsegment_setsegment", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetGhost2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2chainsegment_getghost2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetGhost2__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2chainsegment_setghost2", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
