/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2ContactEvents extends NativeObject {

    private B2ContactBeginTouchEvent B2ContactBeginTouchEvent_TEMP_GEN_0;

    private B2ContactEndTouchEvent B2ContactEndTouchEvent_TEMP_GEN_0;

    private B2ContactHitEvent B2ContactHitEvent_TEMP_GEN_0;

    static public final B2ContactEvents NULL = B2ContactEvents.native_new();

    public B2ContactEvents() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ContactEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ContactEvents native_new() {
        return new B2ContactEvents((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetBeginCount() {
        return internal_native_GetBeginCount(native_address);
    }

    public static int internal_native_GetBeginCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetBeginCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ContactBeginTouchEvent GetBeginEvent(int index) {
        long addr = internal_native_GetBeginEvent_addr(native_address, index);
        if (addr == 0)
            return B2ContactBeginTouchEvent.NULL;
        if (B2ContactBeginTouchEvent_TEMP_GEN_0 == null)
            B2ContactBeginTouchEvent_TEMP_GEN_0 = B2ContactBeginTouchEvent.native_new();
        B2ContactBeginTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B2ContactBeginTouchEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetBeginEvent_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetBeginEvent_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetEndCount() {
        return internal_native_GetEndCount(native_address);
    }

    public static int internal_native_GetEndCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetEndCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ContactEndTouchEvent GetEndEvent(int index) {
        long addr = internal_native_GetEndEvent_addr(native_address, index);
        if (addr == 0)
            return B2ContactEndTouchEvent.NULL;
        if (B2ContactEndTouchEvent_TEMP_GEN_0 == null)
            B2ContactEndTouchEvent_TEMP_GEN_0 = B2ContactEndTouchEvent.native_new();
        B2ContactEndTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B2ContactEndTouchEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetEndEvent_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetEndEvent_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetHitCount() {
        return internal_native_GetHitCount(native_address);
    }

    public static int internal_native_GetHitCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetHitCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ContactHitEvent GetHitEvent(int index) {
        long addr = internal_native_GetHitEvent_addr(native_address, index);
        if (addr == 0)
            return B2ContactHitEvent.NULL;
        if (B2ContactHitEvent_TEMP_GEN_0 == null)
            B2ContactHitEvent_TEMP_GEN_0 = B2ContactHitEvent.native_new();
        B2ContactHitEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B2ContactHitEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetHitEvent_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetHitEvent_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2contactevents_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2contactevents_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBeginCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2contactevents_getbegincount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBeginEvent_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2contactevents_getbeginevent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetEndCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2contactevents_getendcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetEndEvent_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2contactevents_getendevent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetHitCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2contactevents_gethitcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetHitEvent_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2contactevents_gethitevent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
