/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2DebugDrawEm extends NativeObject {

    private B2AABB B2AABB_TEMP_GEN_0;

    static private B2DebugPolygon B2DebugPolygon_TEMP_STATIC_GEN_0;

    static private B2Transform B2Transform_TEMP_STATIC_GEN_0;

    static private B2DebugPolygon B2DebugPolygon_TEMP_STATIC_GEN_1;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_0;

    static private B2Transform B2Transform_TEMP_STATIC_GEN_1;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_1;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_2;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_3;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_4;

    static private B2Transform B2Transform_TEMP_STATIC_GEN_2;

    static private B2Vec2 B2Vec2_TEMP_STATIC_GEN_5;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_DrawPolygon = java.lang.invoke.MethodType.methodType(void.class, long.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawPolygon = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawSolidPolygon = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, float.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawSolidPolygon = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawCircle = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawCircle = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawSolidCircle = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawSolidCircle = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawSolidCapsule = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, float.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawSolidCapsule = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawSegment = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawSegment = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawTransform = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawTransform = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_DrawPoint = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_DrawPoint = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_INT);

    static public final B2DebugDrawEm NULL = B2DebugDrawEm.native_new();

    @Deprecated()
    protected B2DebugDrawEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DebugDrawEm native_new() {
        return new B2DebugDrawEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void DrawWorld(B2World world) {
        internal_native_DrawWorld(native_address, world.native_address);
    }

    public static void internal_native_DrawWorld(long this_addr, long world_addr) {
        try {
            FFMHandles.internal_native_DrawWorld__JJ.invokeExact(this_addr, world_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawingBounds(B2AABB bounds) {
        internal_native_SetDrawingBounds(native_address, bounds.native_address);
    }

    public static void internal_native_SetDrawingBounds(long this_addr, long bounds_addr) {
        try {
            FFMHandles.internal_native_SetDrawingBounds__JJ.invokeExact(this_addr, bounds_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2AABB GetDrawingBounds() {
        long addr = internal_native_GetDrawingBounds_addr(native_address);
        if (addr == 0)
            return B2AABB.NULL;
        if (B2AABB_TEMP_GEN_0 == null)
            B2AABB_TEMP_GEN_0 = B2AABB.native_new();
        B2AABB_TEMP_GEN_0.internal_reset(addr, false);
        return B2AABB_TEMP_GEN_0;
    }

    public static long internal_native_GetDrawingBounds_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetDrawingBounds_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUseDrawingBounds(boolean enabled) {
        internal_native_SetUseDrawingBounds(native_address, enabled);
    }

    public static void internal_native_SetUseDrawingBounds(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetUseDrawingBounds__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetUseDrawingBounds() {
        return internal_native_GetUseDrawingBounds(native_address);
    }

    public static boolean internal_native_GetUseDrawingBounds(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetUseDrawingBounds__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawShapes(boolean enabled) {
        internal_native_SetDrawShapes(native_address, enabled);
    }

    public static void internal_native_SetDrawShapes(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawShapes__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawShapes() {
        return internal_native_GetDrawShapes(native_address);
    }

    public static boolean internal_native_GetDrawShapes(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawShapes__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawJoints(boolean enabled) {
        internal_native_SetDrawJoints(native_address, enabled);
    }

    public static void internal_native_SetDrawJoints(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawJoints__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawJoints() {
        return internal_native_GetDrawJoints(native_address);
    }

    public static boolean internal_native_GetDrawJoints(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawJoints__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawJointExtras(boolean enabled) {
        internal_native_SetDrawJointExtras(native_address, enabled);
    }

    public static void internal_native_SetDrawJointExtras(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawJointExtras__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawJointExtras() {
        return internal_native_GetDrawJointExtras(native_address);
    }

    public static boolean internal_native_GetDrawJointExtras(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawJointExtras__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawBounds(boolean enabled) {
        internal_native_SetDrawBounds(native_address, enabled);
    }

    public static void internal_native_SetDrawBounds(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawBounds__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawBounds() {
        return internal_native_GetDrawBounds(native_address);
    }

    public static boolean internal_native_GetDrawBounds(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawBounds__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawMass(boolean enabled) {
        internal_native_SetDrawMass(native_address, enabled);
    }

    public static void internal_native_SetDrawMass(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawMass__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawMass() {
        return internal_native_GetDrawMass(native_address);
    }

    public static boolean internal_native_GetDrawMass(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawMass__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawBodyNames(boolean enabled) {
        internal_native_SetDrawBodyNames(native_address, enabled);
    }

    public static void internal_native_SetDrawBodyNames(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawBodyNames__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawBodyNames() {
        return internal_native_GetDrawBodyNames(native_address);
    }

    public static boolean internal_native_GetDrawBodyNames(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawBodyNames__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawContacts(boolean enabled) {
        internal_native_SetDrawContacts(native_address, enabled);
    }

    public static void internal_native_SetDrawContacts(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawContacts__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawContacts() {
        return internal_native_GetDrawContacts(native_address);
    }

    public static boolean internal_native_GetDrawContacts(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawContacts__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawGraphColors(boolean enabled) {
        internal_native_SetDrawGraphColors(native_address, enabled);
    }

    public static void internal_native_SetDrawGraphColors(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawGraphColors__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawGraphColors() {
        return internal_native_GetDrawGraphColors(native_address);
    }

    public static boolean internal_native_GetDrawGraphColors(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawGraphColors__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawContactNormals(boolean enabled) {
        internal_native_SetDrawContactNormals(native_address, enabled);
    }

    public static void internal_native_SetDrawContactNormals(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawContactNormals__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawContactNormals() {
        return internal_native_GetDrawContactNormals(native_address);
    }

    public static boolean internal_native_GetDrawContactNormals(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawContactNormals__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawContactImpulses(boolean enabled) {
        internal_native_SetDrawContactImpulses(native_address, enabled);
    }

    public static void internal_native_SetDrawContactImpulses(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawContactImpulses__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawContactImpulses() {
        return internal_native_GetDrawContactImpulses(native_address);
    }

    public static boolean internal_native_GetDrawContactImpulses(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawContactImpulses__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawContactFeatures(boolean enabled) {
        internal_native_SetDrawContactFeatures(native_address, enabled);
    }

    public static void internal_native_SetDrawContactFeatures(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawContactFeatures__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawContactFeatures() {
        return internal_native_GetDrawContactFeatures(native_address);
    }

    public static boolean internal_native_GetDrawContactFeatures(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawContactFeatures__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawFrictionImpulses(boolean enabled) {
        internal_native_SetDrawFrictionImpulses(native_address, enabled);
    }

    public static void internal_native_SetDrawFrictionImpulses(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawFrictionImpulses__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawFrictionImpulses() {
        return internal_native_GetDrawFrictionImpulses(native_address);
    }

    public static boolean internal_native_GetDrawFrictionImpulses(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawFrictionImpulses__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawIslands(boolean enabled) {
        internal_native_SetDrawIslands(native_address, enabled);
    }

    public static void internal_native_SetDrawIslands(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetDrawIslands__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetDrawIslands() {
        return internal_native_GetDrawIslands(native_address);
    }

    public static boolean internal_native_GetDrawIslands(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetDrawIslands__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2DebugDrawEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_DrawPolygon = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawPolygon", callbackMethodType_DrawPolygon).bindTo(this);
            upcallStub_DrawPolygon = callbackLinker.upcallStub(mh_DrawPolygon, callbackDescriptor_DrawPolygon, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawSolidPolygon = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawSolidPolygon", callbackMethodType_DrawSolidPolygon).bindTo(this);
            upcallStub_DrawSolidPolygon = callbackLinker.upcallStub(mh_DrawSolidPolygon, callbackDescriptor_DrawSolidPolygon, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawCircle = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawCircle", callbackMethodType_DrawCircle).bindTo(this);
            upcallStub_DrawCircle = callbackLinker.upcallStub(mh_DrawCircle, callbackDescriptor_DrawCircle, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawSolidCircle = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawSolidCircle", callbackMethodType_DrawSolidCircle).bindTo(this);
            upcallStub_DrawSolidCircle = callbackLinker.upcallStub(mh_DrawSolidCircle, callbackDescriptor_DrawSolidCircle, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawSolidCapsule = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawSolidCapsule", callbackMethodType_DrawSolidCapsule).bindTo(this);
            upcallStub_DrawSolidCapsule = callbackLinker.upcallStub(mh_DrawSolidCapsule, callbackDescriptor_DrawSolidCapsule, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawSegment = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawSegment", callbackMethodType_DrawSegment).bindTo(this);
            upcallStub_DrawSegment = callbackLinker.upcallStub(mh_DrawSegment, callbackDescriptor_DrawSegment, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawTransform = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawTransform", callbackMethodType_DrawTransform).bindTo(this);
            upcallStub_DrawTransform = callbackLinker.upcallStub(mh_DrawTransform, callbackDescriptor_DrawTransform, upcallArena);
            java.lang.invoke.MethodHandle mh_DrawPoint = callbackLookup.findVirtual(B2DebugDrawEm.class, "internal_DrawPoint", callbackMethodType_DrawPoint).bindTo(this);
            upcallStub_DrawPoint = callbackLinker.upcallStub(mh_DrawPoint, callbackDescriptor_DrawPoint, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_DrawPolygon.address(), upcallStub_DrawSolidPolygon.address(), upcallStub_DrawCircle.address(), upcallStub_DrawSolidCircle.address(), upcallStub_DrawSolidCapsule.address(), upcallStub_DrawSegment.address(), upcallStub_DrawTransform.address(), upcallStub_DrawPoint.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void DrawPolygon(B2DebugPolygon polygon, int color) {
    }

    private void internal_DrawPolygon(long polygon_addr, int color) {
        if (B2DebugPolygon_TEMP_STATIC_GEN_0 == null)
            B2DebugPolygon_TEMP_STATIC_GEN_0 = B2DebugPolygon.native_new();
        B2DebugPolygon_TEMP_STATIC_GEN_0.internal_reset(polygon_addr, false);
        DrawPolygon(B2DebugPolygon_TEMP_STATIC_GEN_0, color);
    }

    protected void DrawSolidPolygon(B2Transform transform, B2DebugPolygon polygon, float radius, int color) {
    }

    private void internal_DrawSolidPolygon(long transform_addr, long polygon_addr, float radius, int color) {
        if (B2Transform_TEMP_STATIC_GEN_0 == null)
            B2Transform_TEMP_STATIC_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_STATIC_GEN_0.internal_reset(transform_addr, false);
        if (B2DebugPolygon_TEMP_STATIC_GEN_1 == null)
            B2DebugPolygon_TEMP_STATIC_GEN_1 = B2DebugPolygon.native_new();
        B2DebugPolygon_TEMP_STATIC_GEN_1.internal_reset(polygon_addr, false);
        DrawSolidPolygon(B2Transform_TEMP_STATIC_GEN_0, B2DebugPolygon_TEMP_STATIC_GEN_1, radius, color);
    }

    protected void DrawCircle(B2Vec2 center, float radius, int color) {
    }

    private void internal_DrawCircle(long center_addr, float radius, int color) {
        if (B2Vec2_TEMP_STATIC_GEN_0 == null)
            B2Vec2_TEMP_STATIC_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_0.internal_reset(center_addr, false);
        DrawCircle(B2Vec2_TEMP_STATIC_GEN_0, radius, color);
    }

    protected void DrawSolidCircle(B2Transform transform, float radius, int color) {
    }

    private void internal_DrawSolidCircle(long transform_addr, float radius, int color) {
        if (B2Transform_TEMP_STATIC_GEN_1 == null)
            B2Transform_TEMP_STATIC_GEN_1 = B2Transform.native_new();
        B2Transform_TEMP_STATIC_GEN_1.internal_reset(transform_addr, false);
        DrawSolidCircle(B2Transform_TEMP_STATIC_GEN_1, radius, color);
    }

    protected void DrawSolidCapsule(B2Vec2 p1, B2Vec2 p2, float radius, int color) {
    }

    private void internal_DrawSolidCapsule(long p1_addr, long p2_addr, float radius, int color) {
        if (B2Vec2_TEMP_STATIC_GEN_1 == null)
            B2Vec2_TEMP_STATIC_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_1.internal_reset(p1_addr, false);
        if (B2Vec2_TEMP_STATIC_GEN_2 == null)
            B2Vec2_TEMP_STATIC_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_2.internal_reset(p2_addr, false);
        DrawSolidCapsule(B2Vec2_TEMP_STATIC_GEN_1, B2Vec2_TEMP_STATIC_GEN_2, radius, color);
    }

    protected void DrawSegment(B2Vec2 p1, B2Vec2 p2, int color) {
    }

    private void internal_DrawSegment(long p1_addr, long p2_addr, int color) {
        if (B2Vec2_TEMP_STATIC_GEN_3 == null)
            B2Vec2_TEMP_STATIC_GEN_3 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_3.internal_reset(p1_addr, false);
        if (B2Vec2_TEMP_STATIC_GEN_4 == null)
            B2Vec2_TEMP_STATIC_GEN_4 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_4.internal_reset(p2_addr, false);
        DrawSegment(B2Vec2_TEMP_STATIC_GEN_3, B2Vec2_TEMP_STATIC_GEN_4, color);
    }

    protected void DrawTransform(B2Transform transform) {
    }

    private void internal_DrawTransform(long transform_addr) {
        if (B2Transform_TEMP_STATIC_GEN_2 == null)
            B2Transform_TEMP_STATIC_GEN_2 = B2Transform.native_new();
        B2Transform_TEMP_STATIC_GEN_2.internal_reset(transform_addr, false);
        DrawTransform(B2Transform_TEMP_STATIC_GEN_2);
    }

    protected void DrawPoint(B2Vec2 point, float size, int color) {
    }

    private void internal_DrawPoint(long point_addr, float size, int color) {
        if (B2Vec2_TEMP_STATIC_GEN_5 == null)
            B2Vec2_TEMP_STATIC_GEN_5 = B2Vec2.native_new();
        B2Vec2_TEMP_STATIC_GEN_5.internal_reset(point_addr, false);
        DrawPoint(B2Vec2_TEMP_STATIC_GEN_5, size, color);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_DrawPolygon;

    private MemorySegment upcallStub_DrawSolidPolygon;

    private MemorySegment upcallStub_DrawCircle;

    private MemorySegment upcallStub_DrawSolidCircle;

    private MemorySegment upcallStub_DrawSolidCapsule;

    private MemorySegment upcallStub_DrawSegment;

    private MemorySegment upcallStub_DrawTransform;

    private MemorySegment upcallStub_DrawPoint;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_DrawPolygon = null;
        upcallStub_DrawSolidPolygon = null;
        upcallStub_DrawCircle = null;
        upcallStub_DrawSolidCircle = null;
        upcallStub_DrawSolidCapsule = null;
        upcallStub_DrawSegment = null;
        upcallStub_DrawTransform = null;
        upcallStub_DrawPoint = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long DrawPolygon_fp, long DrawSolidPolygon_fp, long DrawCircle_fp, long DrawSolidCircle_fp, long DrawSolidCapsule_fp, long DrawSegment_fp, long DrawTransform_fp, long DrawPoint_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJJJJJJJ.invokeExact(this_addr, DrawPolygon_fp, DrawSolidPolygon_fp, DrawCircle_fp, DrawSolidCircle_fp, DrawSolidCapsule_fp, DrawSegment_fp, DrawTransform_fp, DrawPoint_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_DrawWorld__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_drawworld", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawingBounds__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawingbounds", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawingBounds_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2debugdrawem_getdrawingbounds_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUseDrawingBounds__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setusedrawingbounds", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetUseDrawingBounds__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getusedrawingbounds", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawShapes__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawshapes", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawShapes__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawshapes", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawJoints__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawjoints", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawJoints__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawjoints", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawJointExtras__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawjointextras", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawJointExtras__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawjointextras", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawBounds__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawbounds", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawBounds__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawbounds", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawMass__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawmass", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawMass__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawmass", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawBodyNames__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawbodynames", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawBodyNames__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawbodynames", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawContacts__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawcontacts", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawContacts__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawcontacts", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawGraphColors__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawgraphcolors", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawGraphColors__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawgraphcolors", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawContactNormals__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawcontactnormals", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawContactNormals__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawcontactnormals", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawContactImpulses__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawcontactimpulses", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawContactImpulses__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawcontactimpulses", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawContactFeatures__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawcontactfeatures", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawContactFeatures__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawcontactfeatures", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawFrictionImpulses__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawfrictionimpulses", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawFrictionImpulses__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawfrictionimpulses", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawIslands__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setdrawislands", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawIslands__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_getdrawislands", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2debugdrawem_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJJJJJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2debugdrawem_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
