/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2DistanceInput extends NativeObject {

    private B2ShapeProxy B2ShapeProxy_TEMP_GEN_0;

    private B2ShapeProxy B2ShapeProxy_TEMP_GEN_1;

    private B2Transform B2Transform_TEMP_GEN_0;

    private B2Transform B2Transform_TEMP_GEN_1;

    static public final B2DistanceInput NULL = B2DistanceInput.native_new();

    public B2DistanceInput() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DistanceInput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DistanceInput native_new() {
        return new B2DistanceInput((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ShapeProxy GetProxyA() {
        long addr = internal_native_GetProxyA_addr(native_address);
        if (addr == 0)
            return B2ShapeProxy.NULL;
        if (B2ShapeProxy_TEMP_GEN_0 == null)
            B2ShapeProxy_TEMP_GEN_0 = B2ShapeProxy.native_new();
        B2ShapeProxy_TEMP_GEN_0.internal_reset(addr, false);
        return B2ShapeProxy_TEMP_GEN_0;
    }

    public static long internal_native_GetProxyA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetProxyA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetProxyA(B2ShapeProxy proxy) {
        internal_native_SetProxyA(native_address, proxy.native_address);
    }

    public static void internal_native_SetProxyA(long this_addr, long proxy_addr) {
        try {
            FFMHandles.internal_native_SetProxyA__JJ.invokeExact(this_addr, proxy_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2ShapeProxy GetProxyB() {
        long addr = internal_native_GetProxyB_addr(native_address);
        if (addr == 0)
            return B2ShapeProxy.NULL;
        if (B2ShapeProxy_TEMP_GEN_1 == null)
            B2ShapeProxy_TEMP_GEN_1 = B2ShapeProxy.native_new();
        B2ShapeProxy_TEMP_GEN_1.internal_reset(addr, false);
        return B2ShapeProxy_TEMP_GEN_1;
    }

    public static long internal_native_GetProxyB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetProxyB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetProxyB(B2ShapeProxy proxy) {
        internal_native_SetProxyB(native_address, proxy.native_address);
    }

    public static void internal_native_SetProxyB(long this_addr, long proxy_addr) {
        try {
            FFMHandles.internal_native_SetProxyB__JJ.invokeExact(this_addr, proxy_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Transform GetTransformA() {
        long addr = internal_native_GetTransformA_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_0 == null)
            B2Transform_TEMP_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransformA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTransformA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTransformA(B2Transform transform) {
        internal_native_SetTransformA(native_address, transform.native_address);
    }

    public static void internal_native_SetTransformA(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetTransformA__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Transform GetTransformB() {
        long addr = internal_native_GetTransformB_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_1 == null)
            B2Transform_TEMP_GEN_1 = B2Transform.native_new();
        B2Transform_TEMP_GEN_1.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_1;
    }

    public static long internal_native_GetTransformB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTransformB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTransformB(B2Transform transform) {
        internal_native_SetTransformB(native_address, transform.native_address);
    }

    public static void internal_native_SetTransformB(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetTransformB__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetUseRadii() {
        return internal_native_GetUseRadii(native_address);
    }

    public static boolean internal_native_GetUseRadii(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetUseRadii__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUseRadii(boolean useRadii) {
        internal_native_SetUseRadii(native_address, useRadii);
    }

    public static void internal_native_SetUseRadii(long this_addr, boolean useRadii) {
        try {
            FFMHandles.internal_native_SetUseRadii__JZ.invokeExact(this_addr, useRadii);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2distanceinput_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetProxyA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2distanceinput_getproxya_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetProxyA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_setproxya", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetProxyB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2distanceinput_getproxyb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetProxyB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_setproxyb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTransformA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2distanceinput_gettransforma_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTransformA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_settransforma", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTransformB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2distanceinput_gettransformb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTransformB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_settransformb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetUseRadii__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_getuseradii", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUseRadii__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2distanceinput_setuseradii", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
