/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2MouseJointDef extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    static public final B2MouseJointDef NULL = B2MouseJointDef.native_new();

    public B2MouseJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2MouseJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2MouseJointDef native_new() {
        return new B2MouseJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdA__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdA__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdB__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdB__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetTarget() {
        long addr = internal_native_GetTarget_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetTarget_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTarget_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTarget(B2Vec2 target) {
        internal_native_SetTarget(native_address, target.native_address);
    }

    public static void internal_native_SetTarget(long this_addr, long target_addr) {
        try {
            FFMHandles.internal_native_SetTarget__JJ.invokeExact(this_addr, target_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetHertz() {
        return internal_native_GetHertz(native_address);
    }

    public static float internal_native_GetHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetHertz(float hertz) {
        internal_native_SetHertz(native_address, hertz);
    }

    public static void internal_native_SetHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDampingRatio() {
        return internal_native_GetDampingRatio(native_address);
    }

    public static float internal_native_GetDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDampingRatio(float ratio) {
        internal_native_SetDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxForce() {
        return internal_native_GetMaxForce(native_address);
    }

    public static float internal_native_GetMaxForce(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxForce__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxForce(float force) {
        internal_native_SetMaxForce(native_address, force);
    }

    public static void internal_native_SetMaxForce(long this_addr, float force) {
        try {
            FFMHandles.internal_native_SetMaxForce__JF.invokeExact(this_addr, force);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetCollideConnected__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        try {
            FFMHandles.internal_native_SetCollideConnected__JZ.invokeExact(this_addr, collide);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2mousejointdef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdA__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_getbodyida", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_setbodyida", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdB__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_getbodyidb", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_setbodyidb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTarget_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2mousejointdef_gettarget_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTarget__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_settarget", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_gethertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_sethertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_getdampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_setdampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxForce__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_getmaxforce", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxForce__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_setmaxforce", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetCollideConnected__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_getcollideconnected", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCollideConnected__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2mousejointdef_setcollideconnected", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
