/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2Polygon extends NativeObject {

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_0;

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_1;

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_2;

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_3;

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_4;

    static private B2Polygon B2Polygon_TEMP_STATIC_GEN_5;

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    private B2MassData B2MassData_TEMP_GEN_0;

    static public final B2Polygon NULL = B2Polygon.native_new();

    public B2Polygon() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Polygon(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Polygon native_new() {
        return new B2Polygon((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateSquare(float halfWidth) {
        long addr = internal_native_CreateSquare_addr(halfWidth);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_0 == null)
            B2Polygon_TEMP_STATIC_GEN_0 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_CreateSquare_addr(float halfWidth) {
        try {
            return (long) FFMHandles.internal_native_CreateSquare_addr__F.invokeExact(halfWidth);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateBox(float halfWidth, float halfHeight) {
        long addr = internal_native_CreateBox_addr(halfWidth, halfHeight);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_1 == null)
            B2Polygon_TEMP_STATIC_GEN_1 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_1.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_1;
    }

    public static long internal_native_CreateBox_addr(float halfWidth, float halfHeight) {
        try {
            return (long) FFMHandles.internal_native_CreateBox_addr__FF.invokeExact(halfWidth, halfHeight);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateRoundedBox(float halfWidth, float halfHeight, float radius) {
        long addr = internal_native_CreateRoundedBox_addr(halfWidth, halfHeight, radius);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_2 == null)
            B2Polygon_TEMP_STATIC_GEN_2 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_2.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_2;
    }

    public static long internal_native_CreateRoundedBox_addr(float halfWidth, float halfHeight, float radius) {
        try {
            return (long) FFMHandles.internal_native_CreateRoundedBox_addr__FFF.invokeExact(halfWidth, halfHeight, radius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateOffsetBox(float halfWidth, float halfHeight, B2Vec2 center, B2Rot rotation) {
        long addr = internal_native_CreateOffsetBox_addr(halfWidth, halfHeight, center.native_address, rotation.native_address);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_3 == null)
            B2Polygon_TEMP_STATIC_GEN_3 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_3.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_3;
    }

    public static long internal_native_CreateOffsetBox_addr(float halfWidth, float halfHeight, long center_addr, long rotation_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateOffsetBox_addr__FFJJ.invokeExact(halfWidth, halfHeight, center_addr, rotation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateOffsetRoundedBox(float halfWidth, float halfHeight, B2Vec2 center, B2Rot rotation, float radius) {
        long addr = internal_native_CreateOffsetRoundedBox_addr(halfWidth, halfHeight, center.native_address, rotation.native_address, radius);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_4 == null)
            B2Polygon_TEMP_STATIC_GEN_4 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_4.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_4;
    }

    public static long internal_native_CreateOffsetRoundedBox_addr(float halfWidth, float halfHeight, long center_addr, long rotation_addr, float radius) {
        try {
            return (long) FFMHandles.internal_native_CreateOffsetRoundedBox_addr__FFJJF.invokeExact(halfWidth, halfHeight, center_addr, rotation_addr, radius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B2Polygon CreateFromHull(B2Hull hull, float radius) {
        long addr = internal_native_CreateFromHull_addr(hull.native_address, radius);
        if (addr == 0)
            return B2Polygon.NULL;
        if (B2Polygon_TEMP_STATIC_GEN_5 == null)
            B2Polygon_TEMP_STATIC_GEN_5 = B2Polygon.native_new();
        B2Polygon_TEMP_STATIC_GEN_5.internal_reset(addr, false);
        return B2Polygon_TEMP_STATIC_GEN_5;
    }

    public static long internal_native_CreateFromHull_addr(long hull_addr, float radius) {
        try {
            return (long) FFMHandles.internal_native_CreateFromHull_addr__JF.invokeExact(hull_addr, radius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetVertexCount() {
        return internal_native_GetVertexCount(native_address);
    }

    public static int internal_native_GetVertexCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetVertexCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetVertex(int index) {
        long addr = internal_native_GetVertex_addr(native_address, index);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetVertex_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetVertex_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetNormal(int index) {
        long addr = internal_native_GetNormal_addr(native_address, index);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetNormal_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetNormal_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetCentroid() {
        long addr = internal_native_GetCentroid_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetCentroid_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetCentroid_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetRadius() {
        return internal_native_GetRadius(native_address);
    }

    public static float internal_native_GetRadius(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetRadius__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetRadius(float radius) {
        internal_native_SetRadius(native_address, radius);
    }

    public static void internal_native_SetRadius(long this_addr, float radius) {
        try {
            FFMHandles.internal_native_SetRadius__JF.invokeExact(this_addr, radius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2MassData ComputeMass(float density) {
        long addr = internal_native_ComputeMass_addr(native_address, density);
        if (addr == 0)
            return B2MassData.NULL;
        if (B2MassData_TEMP_GEN_0 == null)
            B2MassData_TEMP_GEN_0 = B2MassData.native_new();
        B2MassData_TEMP_GEN_0.internal_reset(addr, false);
        return B2MassData_TEMP_GEN_0;
    }

    public static long internal_native_ComputeMass_addr(long this_addr, float density) {
        try {
            return (long) FFMHandles.internal_native_ComputeMass_addr__JF.invokeExact(this_addr, density);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2polygon_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateSquare_addr__F = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createsquare_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_CreateBox_addr__FF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createbox_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_CreateRoundedBox_addr__FFF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createroundedbox_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_CreateOffsetBox_addr__FFJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createoffsetbox_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateOffsetRoundedBox_addr__FFJJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createoffsetroundedbox_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_CreateFromHull_addr__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_createfromhull_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetVertexCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2polygon_getvertexcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetVertex_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_getvertex_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetNormal_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_getnormal_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetCentroid_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_getcentroid_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRadius__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2polygon_getradius", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetRadius__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2polygon_setradius", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_ComputeMass_addr__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2polygon_computemass_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
