/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2PrismaticJointDef extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    static public final B2PrismaticJointDef NULL = B2PrismaticJointDef.native_new();

    public B2PrismaticJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2PrismaticJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2PrismaticJointDef native_new() {
        return new B2PrismaticJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdA__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdA__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdB__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdB__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalAnchorA() {
        long addr = internal_native_GetLocalAnchorA_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalAnchorA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalAnchorA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
        internal_native_SetLocalAnchorA(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorA(long this_addr, long anchor_addr) {
        try {
            FFMHandles.internal_native_SetLocalAnchorA__JJ.invokeExact(this_addr, anchor_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalAnchorB() {
        long addr = internal_native_GetLocalAnchorB_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalAnchorB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalAnchorB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
        internal_native_SetLocalAnchorB(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorB(long this_addr, long anchor_addr) {
        try {
            FFMHandles.internal_native_SetLocalAnchorB__JJ.invokeExact(this_addr, anchor_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Vec2 GetLocalAxisA() {
        long addr = internal_native_GetLocalAxisA_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetLocalAxisA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalAxisA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalAxisA(B2Vec2 axis) {
        internal_native_SetLocalAxisA(native_address, axis.native_address);
    }

    public static void internal_native_SetLocalAxisA(long this_addr, long axis_addr) {
        try {
            FFMHandles.internal_native_SetLocalAxisA__JJ.invokeExact(this_addr, axis_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetReferenceAngle() {
        return internal_native_GetReferenceAngle(native_address);
    }

    public static float internal_native_GetReferenceAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetReferenceAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetReferenceAngle(float angle) {
        internal_native_SetReferenceAngle(native_address, angle);
    }

    public static void internal_native_SetReferenceAngle(long this_addr, float angle) {
        try {
            FFMHandles.internal_native_SetReferenceAngle__JF.invokeExact(this_addr, angle);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTargetTranslation() {
        return internal_native_GetTargetTranslation(native_address);
    }

    public static float internal_native_GetTargetTranslation(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTargetTranslation__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetTranslation(float translation) {
        internal_native_SetTargetTranslation(native_address, translation);
    }

    public static void internal_native_SetTargetTranslation(long this_addr, float translation) {
        try {
            FFMHandles.internal_native_SetTargetTranslation__JF.invokeExact(this_addr, translation);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSpring() {
        return internal_native_GetEnableSpring(native_address);
    }

    public static boolean internal_native_GetEnableSpring(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSpring__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSpring(boolean enabled) {
        internal_native_SetEnableSpring(native_address, enabled);
    }

    public static void internal_native_SetEnableSpring(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSpring__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetHertz() {
        return internal_native_GetHertz(native_address);
    }

    public static float internal_native_GetHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetHertz(float hertz) {
        internal_native_SetHertz(native_address, hertz);
    }

    public static void internal_native_SetHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDampingRatio() {
        return internal_native_GetDampingRatio(native_address);
    }

    public static float internal_native_GetDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDampingRatio(float ratio) {
        internal_native_SetDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableLimit() {
        return internal_native_GetEnableLimit(native_address);
    }

    public static boolean internal_native_GetEnableLimit(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableLimit(boolean enabled) {
        internal_native_SetEnableLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableLimit(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableLimit__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLowerTranslation() {
        return internal_native_GetLowerTranslation(native_address);
    }

    public static float internal_native_GetLowerTranslation(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLowerTranslation__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLowerTranslation(float translation) {
        internal_native_SetLowerTranslation(native_address, translation);
    }

    public static void internal_native_SetLowerTranslation(long this_addr, float translation) {
        try {
            FFMHandles.internal_native_SetLowerTranslation__JF.invokeExact(this_addr, translation);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetUpperTranslation() {
        return internal_native_GetUpperTranslation(native_address);
    }

    public static float internal_native_GetUpperTranslation(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetUpperTranslation__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUpperTranslation(float translation) {
        internal_native_SetUpperTranslation(native_address, translation);
    }

    public static void internal_native_SetUpperTranslation(long this_addr, float translation) {
        try {
            FFMHandles.internal_native_SetUpperTranslation__JF.invokeExact(this_addr, translation);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableMotor() {
        return internal_native_GetEnableMotor(native_address);
    }

    public static boolean internal_native_GetEnableMotor(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableMotor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableMotor(boolean enabled) {
        internal_native_SetEnableMotor(native_address, enabled);
    }

    public static void internal_native_SetEnableMotor(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableMotor__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxMotorForce() {
        return internal_native_GetMaxMotorForce(native_address);
    }

    public static float internal_native_GetMaxMotorForce(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxMotorForce__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxMotorForce(float force) {
        internal_native_SetMaxMotorForce(native_address, force);
    }

    public static void internal_native_SetMaxMotorForce(long this_addr, float force) {
        try {
            FFMHandles.internal_native_SetMaxMotorForce__JF.invokeExact(this_addr, force);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMotorSpeed() {
        return internal_native_GetMotorSpeed(native_address);
    }

    public static float internal_native_GetMotorSpeed(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMotorSpeed__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMotorSpeed(float speed) {
        internal_native_SetMotorSpeed(native_address, speed);
    }

    public static void internal_native_SetMotorSpeed(long this_addr, float speed) {
        try {
            FFMHandles.internal_native_SetMotorSpeed__JF.invokeExact(this_addr, speed);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetCollideConnected__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        try {
            FFMHandles.internal_native_SetCollideConnected__JZ.invokeExact(this_addr, collide);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2prismaticjointdef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdA__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getbodyida", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setbodyida", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdB__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getbodyidb", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setbodyidb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalAnchorA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2prismaticjointdef_getlocalanchora_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalAnchorA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setlocalanchora", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalAnchorB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2prismaticjointdef_getlocalanchorb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalAnchorB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setlocalanchorb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalAxisA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2prismaticjointdef_getlocalaxisa_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalAxisA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setlocalaxisa", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetReferenceAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getreferenceangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetReferenceAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setreferenceangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetTargetTranslation__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_gettargettranslation", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetTranslation__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_settargettranslation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSpring__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getenablespring", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSpring__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setenablespring", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_gethertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_sethertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getdampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setdampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getenablelimit", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableLimit__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setenablelimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetLowerTranslation__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getlowertranslation", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLowerTranslation__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setlowertranslation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetUpperTranslation__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getuppertranslation", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUpperTranslation__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setuppertranslation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableMotor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getenablemotor", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableMotor__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setenablemotor", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxMotorForce__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getmaxmotorforce", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxMotorForce__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setmaxmotorforce", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetMotorSpeed__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getmotorspeed", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMotorSpeed__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setmotorspeed", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetCollideConnected__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_getcollideconnected", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCollideConnected__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2prismaticjointdef_setcollideconnected", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
