/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B2ShapeDef extends NativeObject {

    private B2SurfaceMaterial B2SurfaceMaterial_TEMP_GEN_0;

    private B2Filter B2Filter_TEMP_GEN_0;

    static public final B2ShapeDef NULL = B2ShapeDef.native_new();

    public B2ShapeDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ShapeDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ShapeDef native_new() {
        return new B2ShapeDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2SurfaceMaterial GetMaterial() {
        long addr = internal_native_GetMaterial_addr(native_address);
        if (addr == 0)
            return B2SurfaceMaterial.NULL;
        if (B2SurfaceMaterial_TEMP_GEN_0 == null)
            B2SurfaceMaterial_TEMP_GEN_0 = B2SurfaceMaterial.native_new();
        B2SurfaceMaterial_TEMP_GEN_0.internal_reset(addr, false);
        return B2SurfaceMaterial_TEMP_GEN_0;
    }

    public static long internal_native_GetMaterial_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetMaterial_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaterial(B2SurfaceMaterial material) {
        internal_native_SetMaterial(native_address, material.native_address);
    }

    public static void internal_native_SetMaterial(long this_addr, long material_addr) {
        try {
            FFMHandles.internal_native_SetMaterial__JJ.invokeExact(this_addr, material_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDensity() {
        return internal_native_GetDensity(native_address);
    }

    public static float internal_native_GetDensity(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDensity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDensity(float density) {
        internal_native_SetDensity(native_address, density);
    }

    public static void internal_native_SetDensity(long this_addr, float density) {
        try {
            FFMHandles.internal_native_SetDensity__JF.invokeExact(this_addr, density);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B2Filter GetFilter() {
        long addr = internal_native_GetFilter_addr(native_address);
        if (addr == 0)
            return B2Filter.NULL;
        if (B2Filter_TEMP_GEN_0 == null)
            B2Filter_TEMP_GEN_0 = B2Filter.native_new();
        B2Filter_TEMP_GEN_0.internal_reset(addr, false);
        return B2Filter_TEMP_GEN_0;
    }

    public static long internal_native_GetFilter_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetFilter_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetFilter(B2Filter filter) {
        internal_native_SetFilter(native_address, filter.native_address);
    }

    public static void internal_native_SetFilter(long this_addr, long filter_addr) {
        try {
            FFMHandles.internal_native_SetFilter__JJ.invokeExact(this_addr, filter_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetIsSensor() {
        return internal_native_GetIsSensor(native_address);
    }

    public static boolean internal_native_GetIsSensor(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetIsSensor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetIsSensor(boolean sensor) {
        internal_native_SetIsSensor(native_address, sensor);
    }

    public static void internal_native_SetIsSensor(long this_addr, boolean sensor) {
        try {
            FFMHandles.internal_native_SetIsSensor__JZ.invokeExact(this_addr, sensor);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSensorEvents() {
        return internal_native_GetEnableSensorEvents(native_address);
    }

    public static boolean internal_native_GetEnableSensorEvents(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSensorEvents__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSensorEvents(boolean enabled) {
        internal_native_SetEnableSensorEvents(native_address, enabled);
    }

    public static void internal_native_SetEnableSensorEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSensorEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableContactEvents() {
        return internal_native_GetEnableContactEvents(native_address);
    }

    public static boolean internal_native_GetEnableContactEvents(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableContactEvents__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableContactEvents(boolean enabled) {
        internal_native_SetEnableContactEvents(native_address, enabled);
    }

    public static void internal_native_SetEnableContactEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableContactEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableHitEvents() {
        return internal_native_GetEnableHitEvents(native_address);
    }

    public static boolean internal_native_GetEnableHitEvents(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableHitEvents__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableHitEvents(boolean enabled) {
        internal_native_SetEnableHitEvents(native_address, enabled);
    }

    public static void internal_native_SetEnableHitEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableHitEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnablePreSolveEvents() {
        return internal_native_GetEnablePreSolveEvents(native_address);
    }

    public static boolean internal_native_GetEnablePreSolveEvents(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnablePreSolveEvents__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnablePreSolveEvents(boolean enabled) {
        internal_native_SetEnablePreSolveEvents(native_address, enabled);
    }

    public static void internal_native_SetEnablePreSolveEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnablePreSolveEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetInvokeContactCreation() {
        return internal_native_GetInvokeContactCreation(native_address);
    }

    public static boolean internal_native_GetInvokeContactCreation(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetInvokeContactCreation__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetInvokeContactCreation(boolean enabled) {
        internal_native_SetInvokeContactCreation(native_address, enabled);
    }

    public static void internal_native_SetInvokeContactCreation(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetInvokeContactCreation__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetUpdateBodyMass() {
        return internal_native_GetUpdateBodyMass(native_address);
    }

    public static boolean internal_native_GetUpdateBodyMass(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetUpdateBodyMass__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUpdateBodyMass(boolean enabled) {
        internal_native_SetUpdateBodyMass(native_address, enabled);
    }

    public static void internal_native_SetUpdateBodyMass(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetUpdateBodyMass__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2shapedef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMaterial_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2shapedef_getmaterial_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaterial__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setmaterial", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetDensity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getdensity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDensity__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setdensity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetFilter_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box2d_b2shapedef_getfilter_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFilter__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setfilter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetIsSensor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getissensor", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetIsSensor__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setissensor", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSensorEvents__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getenablesensorevents", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSensorEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setenablesensorevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableContactEvents__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getenablecontactevents", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableContactEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setenablecontactevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableHitEvents__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getenablehitevents", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableHitEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setenablehitevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnablePreSolveEvents__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getenablepresolveevents", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnablePreSolveEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setenablepresolveevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetInvokeContactCreation__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getinvokecontactcreation", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetInvokeContactCreation__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setinvokecontactcreation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetUpdateBodyMass__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_getupdatebodymass", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUpdateBodyMass__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box2d_b2shapedef_setupdatebodymass", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
