/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2 extends NativeObject {

    static public final B2 NULL = B2.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2 native_new() {
        return new B2((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2.internal_native_deleteNative(this_addr);
    }

    public static int StaticBody() {
        return internal_native_StaticBody();
    }

    public static int internal_native_StaticBody() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_StaticBody();
    }

    public static int KinematicBody() {
        return internal_native_KinematicBody();
    }

    public static int internal_native_KinematicBody() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_KinematicBody();
    }

    public static int DynamicBody() {
        return internal_native_DynamicBody();
    }

    public static int internal_native_DynamicBody() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_DynamicBody();
    }

    public static int CircleShape() {
        return internal_native_CircleShape();
    }

    public static int internal_native_CircleShape() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_CircleShape();
    }

    public static int CapsuleShape() {
        return internal_native_CapsuleShape();
    }

    public static int internal_native_CapsuleShape() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_CapsuleShape();
    }

    public static int SegmentShape() {
        return internal_native_SegmentShape();
    }

    public static int internal_native_SegmentShape() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_SegmentShape();
    }

    public static int PolygonShape() {
        return internal_native_PolygonShape();
    }

    public static int internal_native_PolygonShape() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_PolygonShape();
    }

    public static int ChainSegmentShape() {
        return internal_native_ChainSegmentShape();
    }

    public static int internal_native_ChainSegmentShape() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_ChainSegmentShape();
    }

    public static int DistanceJoint() {
        return internal_native_DistanceJoint();
    }

    public static int internal_native_DistanceJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_DistanceJoint();
    }

    public static int FilterJoint() {
        return internal_native_FilterJoint();
    }

    public static int internal_native_FilterJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_FilterJoint();
    }

    public static int MotorJoint() {
        return internal_native_MotorJoint();
    }

    public static int internal_native_MotorJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_MotorJoint();
    }

    public static int MouseJoint() {
        return internal_native_MouseJoint();
    }

    public static int internal_native_MouseJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_MouseJoint();
    }

    public static int PrismaticJoint() {
        return internal_native_PrismaticJoint();
    }

    public static int internal_native_PrismaticJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_PrismaticJoint();
    }

    public static int RevoluteJoint() {
        return internal_native_RevoluteJoint();
    }

    public static int internal_native_RevoluteJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_RevoluteJoint();
    }

    public static int WeldJoint() {
        return internal_native_WeldJoint();
    }

    public static int internal_native_WeldJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_WeldJoint();
    }

    public static int WheelJoint() {
        return internal_native_WheelJoint();
    }

    public static int internal_native_WheelJoint() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_WheelJoint();
    }

    public static int MaxPolygonVertices() {
        return internal_native_MaxPolygonVertices();
    }

    public static int internal_native_MaxPolygonVertices() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_MaxPolygonVertices();
    }

    public static long DefaultCategoryBits() {
        return internal_native_DefaultCategoryBits();
    }

    public static long internal_native_DefaultCategoryBits() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_DefaultCategoryBits();
    }

    public static long DefaultMaskBits() {
        return internal_native_DefaultMaskBits();
    }

    public static long internal_native_DefaultMaskBits() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_DefaultMaskBits();
    }

    public static int VersionMajor() {
        return internal_native_VersionMajor();
    }

    public static int internal_native_VersionMajor() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_VersionMajor();
    }

    public static int VersionMinor() {
        return internal_native_VersionMinor();
    }

    public static int internal_native_VersionMinor() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_VersionMinor();
    }

    public static int VersionRevision() {
        return internal_native_VersionRevision();
    }

    public static int internal_native_VersionRevision() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_VersionRevision();
    }

    public static void SetLengthUnitsPerMeter(float lengthUnits) {
        internal_native_SetLengthUnitsPerMeter(lengthUnits);
    }

    public static void internal_native_SetLengthUnitsPerMeter(float lengthUnits) {
        com.github.xpenatan.box2d.natives.JNI_B2.internal_native_SetLengthUnitsPerMeter(lengthUnits);
    }

    public static float GetLengthUnitsPerMeter() {
        return internal_native_GetLengthUnitsPerMeter();
    }

    public static float internal_native_GetLengthUnitsPerMeter() {
        return com.github.xpenatan.box2d.natives.JNI_B2.internal_native_GetLengthUnitsPerMeter();
    }
}
