/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2AABB extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    private B2Vec2 B2Vec2_TEMP_GEN_3;

    static public final B2AABB NULL = B2AABB.native_new();

    public B2AABB() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_create_addr();
    }

    public B2AABB(B2Vec2 lowerBound, B2Vec2 upperBound) {
        long addr = internal_native_create_B2Vec2_B2Vec2_addr(lowerBound.native_address, upperBound.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B2Vec2_B2Vec2_addr(long lowerBound_addr, long upperBound_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_create_B2Vec2_B2Vec2_addr(lowerBound_addr, upperBound_addr);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2AABB(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2AABB native_new() {
        return new B2AABB((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_deleteNative(this_addr);
    }

    public B2Vec2 GetLowerBound() {
        long addr = internal_native_GetLowerBound_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetLowerBound_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_GetLowerBound_addr(this_addr);
    }

    public void SetLowerBound(B2Vec2 lowerBound) {
        internal_native_SetLowerBound(native_address, lowerBound.native_address);
    }

    public static void internal_native_SetLowerBound(long this_addr, long lowerBound_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_SetLowerBound(this_addr, lowerBound_addr);
    }

    public B2Vec2 GetUpperBound() {
        long addr = internal_native_GetUpperBound_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetUpperBound_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_GetUpperBound_addr(this_addr);
    }

    public void SetUpperBound(B2Vec2 upperBound) {
        internal_native_SetUpperBound(native_address, upperBound.native_address);
    }

    public static void internal_native_SetUpperBound(long this_addr, long upperBound_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_SetUpperBound(this_addr, upperBound_addr);
    }

    public B2Vec2 GetCenter() {
        long addr = internal_native_GetCenter_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetCenter_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_GetCenter_addr(this_addr);
    }

    public B2Vec2 GetExtents() {
        long addr = internal_native_GetExtents_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_3 == null)
            B2Vec2_TEMP_GEN_3 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_3.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_3;
    }

    public static long internal_native_GetExtents_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_GetExtents_addr(this_addr);
    }

    public float GetPerimeter() {
        return internal_native_GetPerimeter(native_address);
    }

    public static float internal_native_GetPerimeter(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_GetPerimeter(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_IsValid(this_addr);
    }

    public boolean Contains(B2AABB other) {
        return internal_native_Contains(native_address, other.native_address);
    }

    public static boolean internal_native_Contains(long this_addr, long other_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2AABB.internal_native_Contains(this_addr, other_addr);
    }
}
