/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2BodyMoveEvent extends NativeObject {

    private B2Transform B2Transform_TEMP_GEN_0;

    static public final B2BodyMoveEvent NULL = B2BodyMoveEvent.native_new();

    public B2BodyMoveEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2BodyMoveEvent.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2BodyMoveEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2BodyMoveEvent native_new() {
        return new B2BodyMoveEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2BodyMoveEvent.internal_native_deleteNative(this_addr);
    }

    public long GetBodyId() {
        return internal_native_GetBodyId(native_address);
    }

    public static long internal_native_GetBodyId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2BodyMoveEvent.internal_native_GetBodyId(this_addr);
    }

    public B2Transform GetTransform() {
        long addr = internal_native_GetTransform_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_0 == null)
            B2Transform_TEMP_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransform_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2BodyMoveEvent.internal_native_GetTransform_addr(this_addr);
    }

    public boolean GetFellAsleep() {
        return internal_native_GetFellAsleep(native_address);
    }

    public static boolean internal_native_GetFellAsleep(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2BodyMoveEvent.internal_native_GetFellAsleep(this_addr);
    }
}
