/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Chain extends NativeObject {

    static public final B2Chain NULL = B2Chain.native_new();

    public B2Chain() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_create_addr();
    }

    public B2Chain(long chainId) {
        long addr = internal_native_create_long_addr(chainId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long chainId) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_create_long_addr(chainId);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Chain(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Chain native_new() {
        return new B2Chain((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_deleteNative(this_addr);
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_GetId(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_IsValid(this_addr);
    }

    public void Destroy() {
        internal_native_Destroy(native_address);
    }

    public static void internal_native_Destroy(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_Destroy(this_addr);
    }

    public int GetSegmentCount() {
        return internal_native_GetSegmentCount(native_address);
    }

    public static int internal_native_GetSegmentCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_GetSegmentCount(this_addr);
    }

    public B2Shape GetSegment(int index) {
        long addr = internal_native_GetSegment_addr(native_address, index);
        if (addr == 0)
            return B2Shape.NULL;
        B2Shape B2Shape_NEW = B2Shape.native_new();
        B2Shape_NEW.internal_reset(addr, true);
        return B2Shape_NEW;
    }

    public static long internal_native_GetSegment_addr(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_GetSegment_addr(this_addr, index);
    }

    public float GetFriction() {
        return internal_native_GetFriction(native_address);
    }

    public static float internal_native_GetFriction(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_GetFriction(this_addr);
    }

    public void SetFriction(float friction) {
        internal_native_SetFriction(native_address, friction);
    }

    public static void internal_native_SetFriction(long this_addr, float friction) {
        com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_SetFriction(this_addr, friction);
    }

    public float GetRestitution() {
        return internal_native_GetRestitution(native_address);
    }

    public static float internal_native_GetRestitution(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_GetRestitution(this_addr);
    }

    public void SetRestitution(float restitution) {
        internal_native_SetRestitution(native_address, restitution);
    }

    public static void internal_native_SetRestitution(long this_addr, float restitution) {
        com.github.xpenatan.box2d.natives.JNI_B2Chain.internal_native_SetRestitution(this_addr, restitution);
    }
}
