/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Collision extends NativeObject {

    static private B2DistanceOutput B2DistanceOutput_TEMP_STATIC_GEN_0;

    static private B2CastResult B2CastResult_TEMP_STATIC_GEN_0;

    static private B2TOIOutput B2TOIOutput_TEMP_STATIC_GEN_0;

    static private B2Transform B2Transform_TEMP_STATIC_GEN_0;

    static private B2CastResult B2CastResult_TEMP_STATIC_GEN_1;

    static private B2CastResult B2CastResult_TEMP_STATIC_GEN_2;

    static private B2CastResult B2CastResult_TEMP_STATIC_GEN_3;

    static private B2CastResult B2CastResult_TEMP_STATIC_GEN_4;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_0;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_1;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_2;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_3;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_4;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_5;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_6;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_7;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_8;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_9;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_10;

    static private B2Manifold B2Manifold_TEMP_STATIC_GEN_11;

    static public final B2Collision NULL = B2Collision.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Collision(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Collision native_new() {
        return new B2Collision((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_deleteNative(this_addr);
    }

    public static B2DistanceOutput ShapeDistance(B2DistanceInput input, B2SimplexCache cache) {
        long addr = internal_native_ShapeDistance_addr(input.native_address, cache.native_address);
        if (addr == 0)
            return B2DistanceOutput.NULL;
        if (B2DistanceOutput_TEMP_STATIC_GEN_0 == null)
            B2DistanceOutput_TEMP_STATIC_GEN_0 = B2DistanceOutput.native_new();
        B2DistanceOutput_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2DistanceOutput_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_ShapeDistance_addr(long input_addr, long cache_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_ShapeDistance_addr(input_addr, cache_addr);
    }

    public static B2CastResult ShapeCast(B2ShapeCastPairInput input) {
        long addr = internal_native_ShapeCast_addr(input.native_address);
        if (addr == 0)
            return B2CastResult.NULL;
        if (B2CastResult_TEMP_STATIC_GEN_0 == null)
            B2CastResult_TEMP_STATIC_GEN_0 = B2CastResult.native_new();
        B2CastResult_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2CastResult_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_ShapeCast_addr(long input_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_ShapeCast_addr(input_addr);
    }

    public static B2TOIOutput TimeOfImpact(B2TOIInput input) {
        long addr = internal_native_TimeOfImpact_addr(input.native_address);
        if (addr == 0)
            return B2TOIOutput.NULL;
        if (B2TOIOutput_TEMP_STATIC_GEN_0 == null)
            B2TOIOutput_TEMP_STATIC_GEN_0 = B2TOIOutput.native_new();
        B2TOIOutput_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2TOIOutput_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_TimeOfImpact_addr(long input_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TimeOfImpact_addr(input_addr);
    }

    public static B2Transform GetSweepTransform(B2Sweep sweep, float time) {
        long addr = internal_native_GetSweepTransform_addr(sweep.native_address, time);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_STATIC_GEN_0 == null)
            B2Transform_TEMP_STATIC_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_GetSweepTransform_addr(long sweep_addr, float time) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_GetSweepTransform_addr(sweep_addr, time);
    }

    public static B2CastResult RayCastCircle(B2Vec2 origin, B2Vec2 translation, float maxFraction, B2Circle circle) {
        long addr = internal_native_RayCastCircle_addr(origin.native_address, translation.native_address, maxFraction, circle.native_address);
        if (addr == 0)
            return B2CastResult.NULL;
        if (B2CastResult_TEMP_STATIC_GEN_1 == null)
            B2CastResult_TEMP_STATIC_GEN_1 = B2CastResult.native_new();
        B2CastResult_TEMP_STATIC_GEN_1.internal_reset(addr, false);
        return B2CastResult_TEMP_STATIC_GEN_1;
    }

    public static long internal_native_RayCastCircle_addr(long origin_addr, long translation_addr, float maxFraction, long circle_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_RayCastCircle_addr(origin_addr, translation_addr, maxFraction, circle_addr);
    }

    public static B2CastResult RayCastCapsule(B2Vec2 origin, B2Vec2 translation, float maxFraction, B2Capsule capsule) {
        long addr = internal_native_RayCastCapsule_addr(origin.native_address, translation.native_address, maxFraction, capsule.native_address);
        if (addr == 0)
            return B2CastResult.NULL;
        if (B2CastResult_TEMP_STATIC_GEN_2 == null)
            B2CastResult_TEMP_STATIC_GEN_2 = B2CastResult.native_new();
        B2CastResult_TEMP_STATIC_GEN_2.internal_reset(addr, false);
        return B2CastResult_TEMP_STATIC_GEN_2;
    }

    public static long internal_native_RayCastCapsule_addr(long origin_addr, long translation_addr, float maxFraction, long capsule_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_RayCastCapsule_addr(origin_addr, translation_addr, maxFraction, capsule_addr);
    }

    public static B2CastResult RayCastSegment(B2Vec2 origin, B2Vec2 translation, float maxFraction, B2Segment segment, boolean oneSided) {
        long addr = internal_native_RayCastSegment_addr(origin.native_address, translation.native_address, maxFraction, segment.native_address, oneSided);
        if (addr == 0)
            return B2CastResult.NULL;
        if (B2CastResult_TEMP_STATIC_GEN_3 == null)
            B2CastResult_TEMP_STATIC_GEN_3 = B2CastResult.native_new();
        B2CastResult_TEMP_STATIC_GEN_3.internal_reset(addr, false);
        return B2CastResult_TEMP_STATIC_GEN_3;
    }

    public static long internal_native_RayCastSegment_addr(long origin_addr, long translation_addr, float maxFraction, long segment_addr, boolean oneSided) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_RayCastSegment_addr(origin_addr, translation_addr, maxFraction, segment_addr, oneSided);
    }

    public static B2CastResult RayCastPolygon(B2Vec2 origin, B2Vec2 translation, float maxFraction, B2Polygon polygon) {
        long addr = internal_native_RayCastPolygon_addr(origin.native_address, translation.native_address, maxFraction, polygon.native_address);
        if (addr == 0)
            return B2CastResult.NULL;
        if (B2CastResult_TEMP_STATIC_GEN_4 == null)
            B2CastResult_TEMP_STATIC_GEN_4 = B2CastResult.native_new();
        B2CastResult_TEMP_STATIC_GEN_4.internal_reset(addr, false);
        return B2CastResult_TEMP_STATIC_GEN_4;
    }

    public static long internal_native_RayCastPolygon_addr(long origin_addr, long translation_addr, float maxFraction, long polygon_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_RayCastPolygon_addr(origin_addr, translation_addr, maxFraction, polygon_addr);
    }

    public static B2Manifold CollideCircles(B2Circle shapeA, B2Transform transformA, B2Circle shapeB, B2Transform transformB) {
        long addr = internal_native_CollideCircles_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_0 == null)
            B2Manifold_TEMP_STATIC_GEN_0 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_CollideCircles_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideCircles_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideCapsuleAndCircle(B2Capsule shapeA, B2Transform transformA, B2Circle shapeB, B2Transform transformB) {
        long addr = internal_native_CollideCapsuleAndCircle_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_1 == null)
            B2Manifold_TEMP_STATIC_GEN_1 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_1.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_1;
    }

    public static long internal_native_CollideCapsuleAndCircle_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideCapsuleAndCircle_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideSegmentAndCircle(B2Segment shapeA, B2Transform transformA, B2Circle shapeB, B2Transform transformB) {
        long addr = internal_native_CollideSegmentAndCircle_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_2 == null)
            B2Manifold_TEMP_STATIC_GEN_2 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_2.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_2;
    }

    public static long internal_native_CollideSegmentAndCircle_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideSegmentAndCircle_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollidePolygonAndCircle(B2Polygon shapeA, B2Transform transformA, B2Circle shapeB, B2Transform transformB) {
        long addr = internal_native_CollidePolygonAndCircle_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_3 == null)
            B2Manifold_TEMP_STATIC_GEN_3 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_3.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_3;
    }

    public static long internal_native_CollidePolygonAndCircle_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollidePolygonAndCircle_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideCapsules(B2Capsule shapeA, B2Transform transformA, B2Capsule shapeB, B2Transform transformB) {
        long addr = internal_native_CollideCapsules_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_4 == null)
            B2Manifold_TEMP_STATIC_GEN_4 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_4.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_4;
    }

    public static long internal_native_CollideCapsules_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideCapsules_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideSegmentAndCapsule(B2Segment shapeA, B2Transform transformA, B2Capsule shapeB, B2Transform transformB) {
        long addr = internal_native_CollideSegmentAndCapsule_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_5 == null)
            B2Manifold_TEMP_STATIC_GEN_5 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_5.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_5;
    }

    public static long internal_native_CollideSegmentAndCapsule_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideSegmentAndCapsule_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollidePolygonAndCapsule(B2Polygon shapeA, B2Transform transformA, B2Capsule shapeB, B2Transform transformB) {
        long addr = internal_native_CollidePolygonAndCapsule_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_6 == null)
            B2Manifold_TEMP_STATIC_GEN_6 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_6.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_6;
    }

    public static long internal_native_CollidePolygonAndCapsule_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollidePolygonAndCapsule_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollidePolygons(B2Polygon shapeA, B2Transform transformA, B2Polygon shapeB, B2Transform transformB) {
        long addr = internal_native_CollidePolygons_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_7 == null)
            B2Manifold_TEMP_STATIC_GEN_7 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_7.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_7;
    }

    public static long internal_native_CollidePolygons_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollidePolygons_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideSegmentAndPolygon(B2Segment shapeA, B2Transform transformA, B2Polygon shapeB, B2Transform transformB) {
        long addr = internal_native_CollideSegmentAndPolygon_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_8 == null)
            B2Manifold_TEMP_STATIC_GEN_8 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_8.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_8;
    }

    public static long internal_native_CollideSegmentAndPolygon_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideSegmentAndPolygon_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideChainSegmentAndCircle(B2ChainSegment shapeA, B2Transform transformA, B2Circle shapeB, B2Transform transformB) {
        long addr = internal_native_CollideChainSegmentAndCircle_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_9 == null)
            B2Manifold_TEMP_STATIC_GEN_9 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_9.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_9;
    }

    public static long internal_native_CollideChainSegmentAndCircle_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideChainSegmentAndCircle_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr);
    }

    public static B2Manifold CollideChainSegmentAndCapsule(B2ChainSegment shapeA, B2Transform transformA, B2Capsule shapeB, B2Transform transformB, B2SimplexCache cache) {
        long addr = internal_native_CollideChainSegmentAndCapsule_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address, cache.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_10 == null)
            B2Manifold_TEMP_STATIC_GEN_10 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_10.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_10;
    }

    public static long internal_native_CollideChainSegmentAndCapsule_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr, long cache_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideChainSegmentAndCapsule_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr, cache_addr);
    }

    public static B2Manifold CollideChainSegmentAndPolygon(B2ChainSegment shapeA, B2Transform transformA, B2Polygon shapeB, B2Transform transformB, B2SimplexCache cache) {
        long addr = internal_native_CollideChainSegmentAndPolygon_addr(shapeA.native_address, transformA.native_address, shapeB.native_address, transformB.native_address, cache.native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_STATIC_GEN_11 == null)
            B2Manifold_TEMP_STATIC_GEN_11 = B2Manifold.native_new();
        B2Manifold_TEMP_STATIC_GEN_11.internal_reset(addr, false);
        return B2Manifold_TEMP_STATIC_GEN_11;
    }

    public static long internal_native_CollideChainSegmentAndPolygon_addr(long shapeA_addr, long transformA_addr, long shapeB_addr, long transformB_addr, long cache_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_CollideChainSegmentAndPolygon_addr(shapeA_addr, transformA_addr, shapeB_addr, transformB_addr, cache_addr);
    }

    public static int TOIUnknown() {
        return internal_native_TOIUnknown();
    }

    public static int internal_native_TOIUnknown() {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TOIUnknown();
    }

    public static int TOIFailed() {
        return internal_native_TOIFailed();
    }

    public static int internal_native_TOIFailed() {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TOIFailed();
    }

    public static int TOIOverlapped() {
        return internal_native_TOIOverlapped();
    }

    public static int internal_native_TOIOverlapped() {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TOIOverlapped();
    }

    public static int TOIHit() {
        return internal_native_TOIHit();
    }

    public static int internal_native_TOIHit() {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TOIHit();
    }

    public static int TOISeparated() {
        return internal_native_TOISeparated();
    }

    public static int internal_native_TOISeparated() {
        return com.github.xpenatan.box2d.natives.JNI_B2Collision.internal_native_TOISeparated();
    }
}
