/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2ContactBeginTouchEvent extends NativeObject {

    private B2Manifold B2Manifold_TEMP_GEN_0;

    static public final B2ContactBeginTouchEvent NULL = B2ContactBeginTouchEvent.native_new();

    public B2ContactBeginTouchEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2ContactBeginTouchEvent.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ContactBeginTouchEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ContactBeginTouchEvent native_new() {
        return new B2ContactBeginTouchEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2ContactBeginTouchEvent.internal_native_deleteNative(this_addr);
    }

    public long GetShapeIdA() {
        return internal_native_GetShapeIdA(native_address);
    }

    public static long internal_native_GetShapeIdA(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2ContactBeginTouchEvent.internal_native_GetShapeIdA(this_addr);
    }

    public long GetShapeIdB() {
        return internal_native_GetShapeIdB(native_address);
    }

    public static long internal_native_GetShapeIdB(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2ContactBeginTouchEvent.internal_native_GetShapeIdB(this_addr);
    }

    public B2Manifold GetManifold() {
        long addr = internal_native_GetManifold_addr(native_address);
        if (addr == 0)
            return B2Manifold.NULL;
        if (B2Manifold_TEMP_GEN_0 == null)
            B2Manifold_TEMP_GEN_0 = B2Manifold.native_new();
        B2Manifold_TEMP_GEN_0.internal_reset(addr, false);
        return B2Manifold_TEMP_GEN_0;
    }

    public static long internal_native_GetManifold_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2ContactBeginTouchEvent.internal_native_GetManifold_addr(this_addr);
    }
}
