/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2DistanceOutput extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    static public final B2DistanceOutput NULL = B2DistanceOutput.native_new();

    public B2DistanceOutput() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DistanceOutput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DistanceOutput native_new() {
        return new B2DistanceOutput((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_deleteNative(this_addr);
    }

    public B2Vec2 GetPointA() {
        long addr = internal_native_GetPointA_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetPointA_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetPointA_addr(this_addr);
    }

    public B2Vec2 GetPointB() {
        long addr = internal_native_GetPointB_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetPointB_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetPointB_addr(this_addr);
    }

    public B2Vec2 GetNormal() {
        long addr = internal_native_GetNormal_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetNormal_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetNormal_addr(this_addr);
    }

    public float GetDistance() {
        return internal_native_GetDistance(native_address);
    }

    public static float internal_native_GetDistance(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetDistance(this_addr);
    }

    public int GetIterations() {
        return internal_native_GetIterations(native_address);
    }

    public static int internal_native_GetIterations(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetIterations(this_addr);
    }

    public int GetSimplexCount() {
        return internal_native_GetSimplexCount(native_address);
    }

    public static int internal_native_GetSimplexCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceOutput.internal_native_GetSimplexCount(this_addr);
    }
}
