/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2DistanceInput extends NativeObject {

    private B2ShapeProxy B2ShapeProxy_TEMP_GEN_0;

    private B2ShapeProxy B2ShapeProxy_TEMP_GEN_1;

    private B2Transform B2Transform_TEMP_GEN_0;

    private B2Transform B2Transform_TEMP_GEN_1;

    static public final B2DistanceInput NULL = B2DistanceInput.native_new();

    public B2DistanceInput() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DistanceInput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DistanceInput native_new() {
        return new B2DistanceInput((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_deleteNative(this_addr);
    }

    public B2ShapeProxy GetProxyA() {
        long addr = internal_native_GetProxyA_addr(native_address);
        if (addr == 0)
            return B2ShapeProxy.NULL;
        if (B2ShapeProxy_TEMP_GEN_0 == null)
            B2ShapeProxy_TEMP_GEN_0 = B2ShapeProxy.native_new();
        B2ShapeProxy_TEMP_GEN_0.internal_reset(addr, false);
        return B2ShapeProxy_TEMP_GEN_0;
    }

    public static long internal_native_GetProxyA_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_GetProxyA_addr(this_addr);
    }

    public void SetProxyA(B2ShapeProxy proxy) {
        internal_native_SetProxyA(native_address, proxy.native_address);
    }

    public static void internal_native_SetProxyA(long this_addr, long proxy_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_SetProxyA(this_addr, proxy_addr);
    }

    public B2ShapeProxy GetProxyB() {
        long addr = internal_native_GetProxyB_addr(native_address);
        if (addr == 0)
            return B2ShapeProxy.NULL;
        if (B2ShapeProxy_TEMP_GEN_1 == null)
            B2ShapeProxy_TEMP_GEN_1 = B2ShapeProxy.native_new();
        B2ShapeProxy_TEMP_GEN_1.internal_reset(addr, false);
        return B2ShapeProxy_TEMP_GEN_1;
    }

    public static long internal_native_GetProxyB_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_GetProxyB_addr(this_addr);
    }

    public void SetProxyB(B2ShapeProxy proxy) {
        internal_native_SetProxyB(native_address, proxy.native_address);
    }

    public static void internal_native_SetProxyB(long this_addr, long proxy_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_SetProxyB(this_addr, proxy_addr);
    }

    public B2Transform GetTransformA() {
        long addr = internal_native_GetTransformA_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_0 == null)
            B2Transform_TEMP_GEN_0 = B2Transform.native_new();
        B2Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransformA_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_GetTransformA_addr(this_addr);
    }

    public void SetTransformA(B2Transform transform) {
        internal_native_SetTransformA(native_address, transform.native_address);
    }

    public static void internal_native_SetTransformA(long this_addr, long transform_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_SetTransformA(this_addr, transform_addr);
    }

    public B2Transform GetTransformB() {
        long addr = internal_native_GetTransformB_addr(native_address);
        if (addr == 0)
            return B2Transform.NULL;
        if (B2Transform_TEMP_GEN_1 == null)
            B2Transform_TEMP_GEN_1 = B2Transform.native_new();
        B2Transform_TEMP_GEN_1.internal_reset(addr, false);
        return B2Transform_TEMP_GEN_1;
    }

    public static long internal_native_GetTransformB_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_GetTransformB_addr(this_addr);
    }

    public void SetTransformB(B2Transform transform) {
        internal_native_SetTransformB(native_address, transform.native_address);
    }

    public static void internal_native_SetTransformB(long this_addr, long transform_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_SetTransformB(this_addr, transform_addr);
    }

    public boolean GetUseRadii() {
        return internal_native_GetUseRadii(native_address);
    }

    public static boolean internal_native_GetUseRadii(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_GetUseRadii(this_addr);
    }

    public void SetUseRadii(boolean useRadii) {
        internal_native_SetUseRadii(native_address, useRadii);
    }

    public static void internal_native_SetUseRadii(long this_addr, boolean useRadii) {
        com.github.xpenatan.box2d.natives.JNI_B2DistanceInput.internal_native_SetUseRadii(this_addr, useRadii);
    }
}
