/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Joint extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    static public final B2Joint NULL = B2Joint.native_new();

    public B2Joint() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_create_addr();
    }

    public B2Joint(long jointId) {
        long addr = internal_native_create_long_addr(jointId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long jointId) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_create_long_addr(jointId);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Joint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Joint native_new() {
        return new B2Joint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_deleteNative(this_addr);
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetId(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_IsValid(this_addr);
    }

    public void Destroy() {
        internal_native_Destroy(native_address);
    }

    public static void internal_native_Destroy(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_Destroy(this_addr);
    }

    public int GetType() {
        return internal_native_GetType(native_address);
    }

    public static int internal_native_GetType(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetType(this_addr);
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetBodyIdA(this_addr);
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetBodyIdB(this_addr);
    }

    public B2Vec2 GetLocalAnchorA() {
        long addr = internal_native_GetLocalAnchorA_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalAnchorA_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetLocalAnchorA_addr(this_addr);
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
        internal_native_SetLocalAnchorA(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorA(long this_addr, long anchor_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_SetLocalAnchorA(this_addr, anchor_addr);
    }

    public B2Vec2 GetLocalAnchorB() {
        long addr = internal_native_GetLocalAnchorB_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalAnchorB_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetLocalAnchorB_addr(this_addr);
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
        internal_native_SetLocalAnchorB(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorB(long this_addr, long anchor_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_SetLocalAnchorB(this_addr, anchor_addr);
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetCollideConnected(this_addr);
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_SetCollideConnected(this_addr, collide);
    }

    public void WakeBodies() {
        internal_native_WakeBodies(native_address);
    }

    public static void internal_native_WakeBodies(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WakeBodies(this_addr);
    }

    public B2Vec2 GetConstraintForce() {
        long addr = internal_native_GetConstraintForce_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_GetConstraintForce_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetConstraintForce_addr(this_addr);
    }

    public float GetConstraintTorque() {
        return internal_native_GetConstraintTorque(native_address);
    }

    public static float internal_native_GetConstraintTorque(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetConstraintTorque(this_addr);
    }

    public float GetLinearSeparation() {
        return internal_native_GetLinearSeparation(native_address);
    }

    public static float internal_native_GetLinearSeparation(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetLinearSeparation(this_addr);
    }

    public float GetAngularSeparation() {
        return internal_native_GetAngularSeparation(native_address);
    }

    public static float internal_native_GetAngularSeparation(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_GetAngularSeparation(this_addr);
    }

    public void DistanceSetLength(float length) {
        internal_native_DistanceSetLength(native_address, length);
    }

    public static void internal_native_DistanceSetLength(long this_addr, float length) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetLength(this_addr, length);
    }

    public float DistanceGetLength() {
        return internal_native_DistanceGetLength(native_address);
    }

    public static float internal_native_DistanceGetLength(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceGetLength(this_addr);
    }

    public void DistanceEnableSpring(boolean enabled) {
        internal_native_DistanceEnableSpring(native_address, enabled);
    }

    public static void internal_native_DistanceEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceEnableSpring(this_addr, enabled);
    }

    public void DistanceSetSpringHertz(float hertz) {
        internal_native_DistanceSetSpringHertz(native_address, hertz);
    }

    public static void internal_native_DistanceSetSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetSpringHertz(this_addr, hertz);
    }

    public void DistanceSetSpringDampingRatio(float ratio) {
        internal_native_DistanceSetSpringDampingRatio(native_address, ratio);
    }

    public static void internal_native_DistanceSetSpringDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetSpringDampingRatio(this_addr, ratio);
    }

    public void DistanceEnableLimit(boolean enabled) {
        internal_native_DistanceEnableLimit(native_address, enabled);
    }

    public static void internal_native_DistanceEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceEnableLimit(this_addr, enabled);
    }

    public void DistanceSetLengthRange(float minLength, float maxLength) {
        internal_native_DistanceSetLengthRange(native_address, minLength, maxLength);
    }

    public static void internal_native_DistanceSetLengthRange(long this_addr, float minLength, float maxLength) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetLengthRange(this_addr, minLength, maxLength);
    }

    public void DistanceEnableMotor(boolean enabled) {
        internal_native_DistanceEnableMotor(native_address, enabled);
    }

    public static void internal_native_DistanceEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceEnableMotor(this_addr, enabled);
    }

    public void DistanceSetMotorSpeed(float speed) {
        internal_native_DistanceSetMotorSpeed(native_address, speed);
    }

    public static void internal_native_DistanceSetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetMotorSpeed(this_addr, speed);
    }

    public void DistanceSetMaxMotorForce(float force) {
        internal_native_DistanceSetMaxMotorForce(native_address, force);
    }

    public static void internal_native_DistanceSetMaxMotorForce(long this_addr, float force) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_DistanceSetMaxMotorForce(this_addr, force);
    }

    public void MotorSetLinearOffset(B2Vec2 offset) {
        internal_native_MotorSetLinearOffset(native_address, offset.native_address);
    }

    public static void internal_native_MotorSetLinearOffset(long this_addr, long offset_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MotorSetLinearOffset(this_addr, offset_addr);
    }

    public void MotorSetAngularOffset(float offset) {
        internal_native_MotorSetAngularOffset(native_address, offset);
    }

    public static void internal_native_MotorSetAngularOffset(long this_addr, float offset) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MotorSetAngularOffset(this_addr, offset);
    }

    public void MotorSetMaxForce(float force) {
        internal_native_MotorSetMaxForce(native_address, force);
    }

    public static void internal_native_MotorSetMaxForce(long this_addr, float force) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MotorSetMaxForce(this_addr, force);
    }

    public void MotorSetMaxTorque(float torque) {
        internal_native_MotorSetMaxTorque(native_address, torque);
    }

    public static void internal_native_MotorSetMaxTorque(long this_addr, float torque) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MotorSetMaxTorque(this_addr, torque);
    }

    public void MotorSetCorrectionFactor(float factor) {
        internal_native_MotorSetCorrectionFactor(native_address, factor);
    }

    public static void internal_native_MotorSetCorrectionFactor(long this_addr, float factor) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MotorSetCorrectionFactor(this_addr, factor);
    }

    public void MouseSetTarget(B2Vec2 target) {
        internal_native_MouseSetTarget(native_address, target.native_address);
    }

    public static void internal_native_MouseSetTarget(long this_addr, long target_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MouseSetTarget(this_addr, target_addr);
    }

    public void MouseSetSpringHertz(float hertz) {
        internal_native_MouseSetSpringHertz(native_address, hertz);
    }

    public static void internal_native_MouseSetSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MouseSetSpringHertz(this_addr, hertz);
    }

    public void MouseSetSpringDampingRatio(float ratio) {
        internal_native_MouseSetSpringDampingRatio(native_address, ratio);
    }

    public static void internal_native_MouseSetSpringDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MouseSetSpringDampingRatio(this_addr, ratio);
    }

    public void MouseSetMaxForce(float force) {
        internal_native_MouseSetMaxForce(native_address, force);
    }

    public static void internal_native_MouseSetMaxForce(long this_addr, float force) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_MouseSetMaxForce(this_addr, force);
    }

    public void PrismaticEnableSpring(boolean enabled) {
        internal_native_PrismaticEnableSpring(native_address, enabled);
    }

    public static void internal_native_PrismaticEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticEnableSpring(this_addr, enabled);
    }

    public void PrismaticSetSpringHertz(float hertz) {
        internal_native_PrismaticSetSpringHertz(native_address, hertz);
    }

    public static void internal_native_PrismaticSetSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetSpringHertz(this_addr, hertz);
    }

    public void PrismaticSetSpringDampingRatio(float ratio) {
        internal_native_PrismaticSetSpringDampingRatio(native_address, ratio);
    }

    public static void internal_native_PrismaticSetSpringDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetSpringDampingRatio(this_addr, ratio);
    }

    public void PrismaticSetTargetTranslation(float translation) {
        internal_native_PrismaticSetTargetTranslation(native_address, translation);
    }

    public static void internal_native_PrismaticSetTargetTranslation(long this_addr, float translation) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetTargetTranslation(this_addr, translation);
    }

    public void PrismaticEnableLimit(boolean enabled) {
        internal_native_PrismaticEnableLimit(native_address, enabled);
    }

    public static void internal_native_PrismaticEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticEnableLimit(this_addr, enabled);
    }

    public void PrismaticSetLimits(float lower, float upper) {
        internal_native_PrismaticSetLimits(native_address, lower, upper);
    }

    public static void internal_native_PrismaticSetLimits(long this_addr, float lower, float upper) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetLimits(this_addr, lower, upper);
    }

    public void PrismaticEnableMotor(boolean enabled) {
        internal_native_PrismaticEnableMotor(native_address, enabled);
    }

    public static void internal_native_PrismaticEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticEnableMotor(this_addr, enabled);
    }

    public void PrismaticSetMotorSpeed(float speed) {
        internal_native_PrismaticSetMotorSpeed(native_address, speed);
    }

    public static void internal_native_PrismaticSetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetMotorSpeed(this_addr, speed);
    }

    public void PrismaticSetMaxMotorForce(float force) {
        internal_native_PrismaticSetMaxMotorForce(native_address, force);
    }

    public static void internal_native_PrismaticSetMaxMotorForce(long this_addr, float force) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticSetMaxMotorForce(this_addr, force);
    }

    public float PrismaticGetTranslation() {
        return internal_native_PrismaticGetTranslation(native_address);
    }

    public static float internal_native_PrismaticGetTranslation(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_PrismaticGetTranslation(this_addr);
    }

    public void RevoluteEnableSpring(boolean enabled) {
        internal_native_RevoluteEnableSpring(native_address, enabled);
    }

    public static void internal_native_RevoluteEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteEnableSpring(this_addr, enabled);
    }

    public void RevoluteSetSpringHertz(float hertz) {
        internal_native_RevoluteSetSpringHertz(native_address, hertz);
    }

    public static void internal_native_RevoluteSetSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetSpringHertz(this_addr, hertz);
    }

    public void RevoluteSetSpringDampingRatio(float ratio) {
        internal_native_RevoluteSetSpringDampingRatio(native_address, ratio);
    }

    public static void internal_native_RevoluteSetSpringDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetSpringDampingRatio(this_addr, ratio);
    }

    public void RevoluteSetTargetAngle(float angle) {
        internal_native_RevoluteSetTargetAngle(native_address, angle);
    }

    public static void internal_native_RevoluteSetTargetAngle(long this_addr, float angle) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetTargetAngle(this_addr, angle);
    }

    public void RevoluteEnableLimit(boolean enabled) {
        internal_native_RevoluteEnableLimit(native_address, enabled);
    }

    public static void internal_native_RevoluteEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteEnableLimit(this_addr, enabled);
    }

    public void RevoluteSetLimits(float lower, float upper) {
        internal_native_RevoluteSetLimits(native_address, lower, upper);
    }

    public static void internal_native_RevoluteSetLimits(long this_addr, float lower, float upper) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetLimits(this_addr, lower, upper);
    }

    public void RevoluteEnableMotor(boolean enabled) {
        internal_native_RevoluteEnableMotor(native_address, enabled);
    }

    public static void internal_native_RevoluteEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteEnableMotor(this_addr, enabled);
    }

    public void RevoluteSetMotorSpeed(float speed) {
        internal_native_RevoluteSetMotorSpeed(native_address, speed);
    }

    public static void internal_native_RevoluteSetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetMotorSpeed(this_addr, speed);
    }

    public void RevoluteSetMaxMotorTorque(float torque) {
        internal_native_RevoluteSetMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_RevoluteSetMaxMotorTorque(long this_addr, float torque) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteSetMaxMotorTorque(this_addr, torque);
    }

    public float RevoluteGetAngle() {
        return internal_native_RevoluteGetAngle(native_address);
    }

    public static float internal_native_RevoluteGetAngle(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_RevoluteGetAngle(this_addr);
    }

    public void WheelEnableSpring(boolean enabled) {
        internal_native_WheelEnableSpring(native_address, enabled);
    }

    public static void internal_native_WheelEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelEnableSpring(this_addr, enabled);
    }

    public void WheelSetSpringHertz(float hertz) {
        internal_native_WheelSetSpringHertz(native_address, hertz);
    }

    public static void internal_native_WheelSetSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelSetSpringHertz(this_addr, hertz);
    }

    public void WheelSetSpringDampingRatio(float ratio) {
        internal_native_WheelSetSpringDampingRatio(native_address, ratio);
    }

    public static void internal_native_WheelSetSpringDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelSetSpringDampingRatio(this_addr, ratio);
    }

    public void WheelEnableLimit(boolean enabled) {
        internal_native_WheelEnableLimit(native_address, enabled);
    }

    public static void internal_native_WheelEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelEnableLimit(this_addr, enabled);
    }

    public void WheelSetLimits(float lower, float upper) {
        internal_native_WheelSetLimits(native_address, lower, upper);
    }

    public static void internal_native_WheelSetLimits(long this_addr, float lower, float upper) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelSetLimits(this_addr, lower, upper);
    }

    public void WheelEnableMotor(boolean enabled) {
        internal_native_WheelEnableMotor(native_address, enabled);
    }

    public static void internal_native_WheelEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelEnableMotor(this_addr, enabled);
    }

    public void WheelSetMotorSpeed(float speed) {
        internal_native_WheelSetMotorSpeed(native_address, speed);
    }

    public static void internal_native_WheelSetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelSetMotorSpeed(this_addr, speed);
    }

    public void WheelSetMaxMotorTorque(float torque) {
        internal_native_WheelSetMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_WheelSetMaxMotorTorque(long this_addr, float torque) {
        com.github.xpenatan.box2d.natives.JNI_B2Joint.internal_native_WheelSetMaxMotorTorque(this_addr, torque);
    }
}
