/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2MassData extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    static public final B2MassData NULL = B2MassData.native_new();

    public B2MassData() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2MassData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2MassData native_new() {
        return new B2MassData((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_deleteNative(this_addr);
    }

    public float GetMass() {
        return internal_native_GetMass(native_address);
    }

    public static float internal_native_GetMass(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_GetMass(this_addr);
    }

    public void SetMass(float mass) {
        internal_native_SetMass(native_address, mass);
    }

    public static void internal_native_SetMass(long this_addr, float mass) {
        com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_SetMass(this_addr, mass);
    }

    public B2Vec2 GetCenter() {
        long addr = internal_native_GetCenter_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetCenter_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_GetCenter_addr(this_addr);
    }

    public void SetCenter(B2Vec2 center) {
        internal_native_SetCenter(native_address, center.native_address);
    }

    public static void internal_native_SetCenter(long this_addr, long center_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_SetCenter(this_addr, center_addr);
    }

    public float GetRotationalInertia() {
        return internal_native_GetRotationalInertia(native_address);
    }

    public static float internal_native_GetRotationalInertia(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_GetRotationalInertia(this_addr);
    }

    public void SetRotationalInertia(float inertia) {
        internal_native_SetRotationalInertia(native_address, inertia);
    }

    public static void internal_native_SetRotationalInertia(long this_addr, float inertia) {
        com.github.xpenatan.box2d.natives.JNI_B2MassData.internal_native_SetRotationalInertia(this_addr, inertia);
    }
}
