/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2RevoluteJointDef extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    static public final B2RevoluteJointDef NULL = B2RevoluteJointDef.native_new();

    public B2RevoluteJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2RevoluteJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2RevoluteJointDef native_new() {
        return new B2RevoluteJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_deleteNative(this_addr);
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetBodyIdA(this_addr);
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetBodyIdA(this_addr, bodyId);
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetBodyIdB(this_addr);
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetBodyIdB(this_addr, bodyId);
    }

    public B2Vec2 GetLocalAnchorA() {
        long addr = internal_native_GetLocalAnchorA_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalAnchorA_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetLocalAnchorA_addr(this_addr);
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
        internal_native_SetLocalAnchorA(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorA(long this_addr, long anchor_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetLocalAnchorA(this_addr, anchor_addr);
    }

    public B2Vec2 GetLocalAnchorB() {
        long addr = internal_native_GetLocalAnchorB_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalAnchorB_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetLocalAnchorB_addr(this_addr);
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
        internal_native_SetLocalAnchorB(native_address, anchor.native_address);
    }

    public static void internal_native_SetLocalAnchorB(long this_addr, long anchor_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetLocalAnchorB(this_addr, anchor_addr);
    }

    public float GetReferenceAngle() {
        return internal_native_GetReferenceAngle(native_address);
    }

    public static float internal_native_GetReferenceAngle(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetReferenceAngle(this_addr);
    }

    public void SetReferenceAngle(float angle) {
        internal_native_SetReferenceAngle(native_address, angle);
    }

    public static void internal_native_SetReferenceAngle(long this_addr, float angle) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetReferenceAngle(this_addr, angle);
    }

    public float GetTargetAngle() {
        return internal_native_GetTargetAngle(native_address);
    }

    public static float internal_native_GetTargetAngle(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetTargetAngle(this_addr);
    }

    public void SetTargetAngle(float angle) {
        internal_native_SetTargetAngle(native_address, angle);
    }

    public static void internal_native_SetTargetAngle(long this_addr, float angle) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetTargetAngle(this_addr, angle);
    }

    public boolean GetEnableSpring() {
        return internal_native_GetEnableSpring(native_address);
    }

    public static boolean internal_native_GetEnableSpring(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetEnableSpring(this_addr);
    }

    public void SetEnableSpring(boolean enabled) {
        internal_native_SetEnableSpring(native_address, enabled);
    }

    public static void internal_native_SetEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetEnableSpring(this_addr, enabled);
    }

    public float GetHertz() {
        return internal_native_GetHertz(native_address);
    }

    public static float internal_native_GetHertz(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetHertz(this_addr);
    }

    public void SetHertz(float hertz) {
        internal_native_SetHertz(native_address, hertz);
    }

    public static void internal_native_SetHertz(long this_addr, float hertz) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetHertz(this_addr, hertz);
    }

    public float GetDampingRatio() {
        return internal_native_GetDampingRatio(native_address);
    }

    public static float internal_native_GetDampingRatio(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetDampingRatio(this_addr);
    }

    public void SetDampingRatio(float ratio) {
        internal_native_SetDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetDampingRatio(this_addr, ratio);
    }

    public boolean GetEnableLimit() {
        return internal_native_GetEnableLimit(native_address);
    }

    public static boolean internal_native_GetEnableLimit(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetEnableLimit(this_addr);
    }

    public void SetEnableLimit(boolean enabled) {
        internal_native_SetEnableLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetEnableLimit(this_addr, enabled);
    }

    public float GetLowerAngle() {
        return internal_native_GetLowerAngle(native_address);
    }

    public static float internal_native_GetLowerAngle(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetLowerAngle(this_addr);
    }

    public void SetLowerAngle(float angle) {
        internal_native_SetLowerAngle(native_address, angle);
    }

    public static void internal_native_SetLowerAngle(long this_addr, float angle) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetLowerAngle(this_addr, angle);
    }

    public float GetUpperAngle() {
        return internal_native_GetUpperAngle(native_address);
    }

    public static float internal_native_GetUpperAngle(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetUpperAngle(this_addr);
    }

    public void SetUpperAngle(float angle) {
        internal_native_SetUpperAngle(native_address, angle);
    }

    public static void internal_native_SetUpperAngle(long this_addr, float angle) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetUpperAngle(this_addr, angle);
    }

    public boolean GetEnableMotor() {
        return internal_native_GetEnableMotor(native_address);
    }

    public static boolean internal_native_GetEnableMotor(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetEnableMotor(this_addr);
    }

    public void SetEnableMotor(boolean enabled) {
        internal_native_SetEnableMotor(native_address, enabled);
    }

    public static void internal_native_SetEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetEnableMotor(this_addr, enabled);
    }

    public float GetMaxMotorTorque() {
        return internal_native_GetMaxMotorTorque(native_address);
    }

    public static float internal_native_GetMaxMotorTorque(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetMaxMotorTorque(this_addr);
    }

    public void SetMaxMotorTorque(float torque) {
        internal_native_SetMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_SetMaxMotorTorque(long this_addr, float torque) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetMaxMotorTorque(this_addr, torque);
    }

    public float GetMotorSpeed() {
        return internal_native_GetMotorSpeed(native_address);
    }

    public static float internal_native_GetMotorSpeed(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetMotorSpeed(this_addr);
    }

    public void SetMotorSpeed(float speed) {
        internal_native_SetMotorSpeed(native_address, speed);
    }

    public static void internal_native_SetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetMotorSpeed(this_addr, speed);
    }

    public float GetDrawSize() {
        return internal_native_GetDrawSize(native_address);
    }

    public static float internal_native_GetDrawSize(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetDrawSize(this_addr);
    }

    public void SetDrawSize(float size) {
        internal_native_SetDrawSize(native_address, size);
    }

    public static void internal_native_SetDrawSize(long this_addr, float size) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetDrawSize(this_addr, size);
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_GetCollideConnected(this_addr);
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        com.github.xpenatan.box2d.natives.JNI_B2RevoluteJointDef.internal_native_SetCollideConnected(this_addr, collide);
    }
}
