/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SensorEndTouchEvent extends NativeObject {

    static public final B2SensorEndTouchEvent NULL = B2SensorEndTouchEvent.native_new();

    public B2SensorEndTouchEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEndTouchEvent.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SensorEndTouchEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SensorEndTouchEvent native_new() {
        return new B2SensorEndTouchEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2SensorEndTouchEvent.internal_native_deleteNative(this_addr);
    }

    public long GetSensorShapeId() {
        return internal_native_GetSensorShapeId(native_address);
    }

    public static long internal_native_GetSensorShapeId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEndTouchEvent.internal_native_GetSensorShapeId(this_addr);
    }

    public long GetVisitorShapeId() {
        return internal_native_GetVisitorShapeId(native_address);
    }

    public static long internal_native_GetVisitorShapeId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEndTouchEvent.internal_native_GetVisitorShapeId(this_addr);
    }
}
