/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SensorEvents extends NativeObject {

    private B2SensorBeginTouchEvent B2SensorBeginTouchEvent_TEMP_GEN_0;

    private B2SensorEndTouchEvent B2SensorEndTouchEvent_TEMP_GEN_0;

    static public final B2SensorEvents NULL = B2SensorEvents.native_new();

    public B2SensorEvents() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SensorEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SensorEvents native_new() {
        return new B2SensorEvents((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_deleteNative(this_addr);
    }

    public int GetBeginCount() {
        return internal_native_GetBeginCount(native_address);
    }

    public static int internal_native_GetBeginCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_GetBeginCount(this_addr);
    }

    public B2SensorBeginTouchEvent GetBeginEvent(int index) {
        long addr = internal_native_GetBeginEvent_addr(native_address, index);
        if (addr == 0)
            return B2SensorBeginTouchEvent.NULL;
        if (B2SensorBeginTouchEvent_TEMP_GEN_0 == null)
            B2SensorBeginTouchEvent_TEMP_GEN_0 = B2SensorBeginTouchEvent.native_new();
        B2SensorBeginTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B2SensorBeginTouchEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetBeginEvent_addr(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_GetBeginEvent_addr(this_addr, index);
    }

    public int GetEndCount() {
        return internal_native_GetEndCount(native_address);
    }

    public static int internal_native_GetEndCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_GetEndCount(this_addr);
    }

    public B2SensorEndTouchEvent GetEndEvent(int index) {
        long addr = internal_native_GetEndEvent_addr(native_address, index);
        if (addr == 0)
            return B2SensorEndTouchEvent.NULL;
        if (B2SensorEndTouchEvent_TEMP_GEN_0 == null)
            B2SensorEndTouchEvent_TEMP_GEN_0 = B2SensorEndTouchEvent.native_new();
        B2SensorEndTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B2SensorEndTouchEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetEndEvent_addr(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2SensorEvents.internal_native_GetEndEvent_addr(this_addr, index);
    }
}
