/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SimplexCache extends NativeObject {

    static public final B2SimplexCache NULL = B2SimplexCache.native_new();

    public B2SimplexCache() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2SimplexCache.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SimplexCache(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SimplexCache native_new() {
        return new B2SimplexCache((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2SimplexCache.internal_native_deleteNative(this_addr);
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2SimplexCache.internal_native_Clear(this_addr);
    }

    public int GetCount() {
        return internal_native_GetCount(native_address);
    }

    public static int internal_native_GetCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SimplexCache.internal_native_GetCount(this_addr);
    }
}
