/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SurfaceMaterial extends NativeObject {

    static public final B2SurfaceMaterial NULL = B2SurfaceMaterial.native_new();

    public B2SurfaceMaterial() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SurfaceMaterial(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SurfaceMaterial native_new() {
        return new B2SurfaceMaterial((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_deleteNative(this_addr);
    }

    public float GetFriction() {
        return internal_native_GetFriction(native_address);
    }

    public static float internal_native_GetFriction(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetFriction(this_addr);
    }

    public void SetFriction(float friction) {
        internal_native_SetFriction(native_address, friction);
    }

    public static void internal_native_SetFriction(long this_addr, float friction) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetFriction(this_addr, friction);
    }

    public float GetRestitution() {
        return internal_native_GetRestitution(native_address);
    }

    public static float internal_native_GetRestitution(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetRestitution(this_addr);
    }

    public void SetRestitution(float restitution) {
        internal_native_SetRestitution(native_address, restitution);
    }

    public static void internal_native_SetRestitution(long this_addr, float restitution) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetRestitution(this_addr, restitution);
    }

    public float GetRollingResistance() {
        return internal_native_GetRollingResistance(native_address);
    }

    public static float internal_native_GetRollingResistance(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetRollingResistance(this_addr);
    }

    public void SetRollingResistance(float resistance) {
        internal_native_SetRollingResistance(native_address, resistance);
    }

    public static void internal_native_SetRollingResistance(long this_addr, float resistance) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetRollingResistance(this_addr, resistance);
    }

    public float GetTangentSpeed() {
        return internal_native_GetTangentSpeed(native_address);
    }

    public static float internal_native_GetTangentSpeed(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetTangentSpeed(this_addr);
    }

    public void SetTangentSpeed(float speed) {
        internal_native_SetTangentSpeed(native_address, speed);
    }

    public static void internal_native_SetTangentSpeed(long this_addr, float speed) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetTangentSpeed(this_addr, speed);
    }

    public int GetUserMaterialId() {
        return internal_native_GetUserMaterialId(native_address);
    }

    public static int internal_native_GetUserMaterialId(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetUserMaterialId(this_addr);
    }

    public void SetUserMaterialId(int materialId) {
        internal_native_SetUserMaterialId(native_address, materialId);
    }

    public static void internal_native_SetUserMaterialId(long this_addr, int materialId) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetUserMaterialId(this_addr, materialId);
    }

    public int GetCustomColor() {
        return internal_native_GetCustomColor(native_address);
    }

    public static int internal_native_GetCustomColor(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_GetCustomColor(this_addr);
    }

    public void SetCustomColor(int color) {
        internal_native_SetCustomColor(native_address, color);
    }

    public static void internal_native_SetCustomColor(long this_addr, int color) {
        com.github.xpenatan.box2d.natives.JNI_B2SurfaceMaterial.internal_native_SetCustomColor(this_addr, color);
    }
}
