/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2TreeResult extends NativeObject {

    static public final B2TreeResult NULL = B2TreeResult.native_new();

    public B2TreeResult() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2TreeResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2TreeResult native_new() {
        return new B2TreeResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_deleteNative(this_addr);
    }

    public int GetCount() {
        return internal_native_GetCount(native_address);
    }

    public static int internal_native_GetCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_GetCount(this_addr);
    }

    public int GetProxyId(int index) {
        return internal_native_GetProxyId(native_address, index);
    }

    public static int internal_native_GetProxyId(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_GetProxyId(this_addr, index);
    }

    public long GetUserData(int index) {
        return internal_native_GetUserData(native_address, index);
    }

    public static long internal_native_GetUserData(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_GetUserData(this_addr, index);
    }

    public int GetNodeVisits() {
        return internal_native_GetNodeVisits(native_address);
    }

    public static int internal_native_GetNodeVisits(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_GetNodeVisits(this_addr);
    }

    public int GetLeafVisits() {
        return internal_native_GetLeafVisits(native_address);
    }

    public static int internal_native_GetLeafVisits(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2TreeResult.internal_native_GetLeafVisits(this_addr);
    }
}
