/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Transform extends NativeObject {

    private B2Vec2 B2Vec2_TEMP_GEN_0;

    private B2Rot B2Rot_TEMP_GEN_0;

    private B2Vec2 B2Vec2_TEMP_GEN_1;

    private B2Vec2 B2Vec2_TEMP_GEN_2;

    static public final B2Transform NULL = B2Transform.native_new();

    public B2Transform() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_create_addr();
    }

    public B2Transform(B2Vec2 position, B2Rot rotation) {
        long addr = internal_native_create_B2Vec2_B2Rot_addr(position.native_address, rotation.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B2Vec2_B2Rot_addr(long position_addr, long rotation_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_create_B2Vec2_B2Rot_addr(position_addr, rotation_addr);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Transform(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Transform native_new() {
        return new B2Transform((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_deleteNative(this_addr);
    }

    public B2Vec2 GetPosition() {
        long addr = internal_native_GetPosition_addr(native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_0 == null)
            B2Vec2_TEMP_GEN_0 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_0.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_0;
    }

    public static long internal_native_GetPosition_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_GetPosition_addr(this_addr);
    }

    public void SetPosition(B2Vec2 position) {
        internal_native_SetPosition(native_address, position.native_address);
    }

    public static void internal_native_SetPosition(long this_addr, long position_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_SetPosition(this_addr, position_addr);
    }

    public B2Rot GetRotation() {
        long addr = internal_native_GetRotation_addr(native_address);
        if (addr == 0)
            return B2Rot.NULL;
        if (B2Rot_TEMP_GEN_0 == null)
            B2Rot_TEMP_GEN_0 = B2Rot.native_new();
        B2Rot_TEMP_GEN_0.internal_reset(addr, false);
        return B2Rot_TEMP_GEN_0;
    }

    public static long internal_native_GetRotation_addr(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_GetRotation_addr(this_addr);
    }

    public void SetRotation(B2Rot rotation) {
        internal_native_SetRotation(native_address, rotation.native_address);
    }

    public static void internal_native_SetRotation(long this_addr, long rotation_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_SetRotation(this_addr, rotation_addr);
    }

    public B2Vec2 TransformPoint(B2Vec2 point) {
        long addr = internal_native_TransformPoint_addr(native_address, point.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_1 == null)
            B2Vec2_TEMP_GEN_1 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_1.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_1;
    }

    public static long internal_native_TransformPoint_addr(long this_addr, long point_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_TransformPoint_addr(this_addr, point_addr);
    }

    public B2Vec2 InverseTransformPoint(B2Vec2 point) {
        long addr = internal_native_InverseTransformPoint_addr(native_address, point.native_address);
        if (addr == 0)
            return B2Vec2.NULL;
        if (B2Vec2_TEMP_GEN_2 == null)
            B2Vec2_TEMP_GEN_2 = B2Vec2.native_new();
        B2Vec2_TEMP_GEN_2.internal_reset(addr, false);
        return B2Vec2_TEMP_GEN_2;
    }

    public static long internal_native_InverseTransformPoint_addr(long this_addr, long point_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2Transform.internal_native_InverseTransformPoint_addr(this_addr, point_addr);
    }
}
