/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2WorldOverlapResult extends NativeObject {

    static public final B2WorldOverlapResult NULL = B2WorldOverlapResult.native_new();

    public B2WorldOverlapResult() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2WorldOverlapResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2WorldOverlapResult native_new() {
        return new B2WorldOverlapResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_deleteNative(this_addr);
    }

    public int GetShapeCount() {
        return internal_native_GetShapeCount(native_address);
    }

    public static int internal_native_GetShapeCount(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_GetShapeCount(this_addr);
    }

    public long GetShapeId(int index) {
        return internal_native_GetShapeId(native_address, index);
    }

    public static long internal_native_GetShapeId(long this_addr, int index) {
        return com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_GetShapeId(this_addr, index);
    }

    public int GetNodeVisits() {
        return internal_native_GetNodeVisits(native_address);
    }

    public static int internal_native_GetNodeVisits(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_GetNodeVisits(this_addr);
    }

    public int GetLeafVisits() {
        return internal_native_GetLeafVisits(native_address);
    }

    public static int internal_native_GetLeafVisits(long this_addr) {
        return com.github.xpenatan.box2d.natives.JNI_B2WorldOverlapResult.internal_native_GetLeafVisits(this_addr);
    }
}
