/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2AABB extends NativeObject {

    static public final B2AABB NULL = B2AABB.native_new();

    public B2AABB() {
    }

    public B2AABB(B2Vec2 lowerBound, B2Vec2 upperBound) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2AABB(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2AABB native_new() {
        return new B2AABB((byte) 0, (char) 0);
    }

    public B2Vec2 GetLowerBound() {
        return null;
    }

    public void SetLowerBound(B2Vec2 lowerBound) {
    }

    public B2Vec2 GetUpperBound() {
        return null;
    }

    public void SetUpperBound(B2Vec2 upperBound) {
    }

    public B2Vec2 GetCenter() {
        return null;
    }

    public B2Vec2 GetExtents() {
        return null;
    }

    public float GetPerimeter() {
        return 0;
    }

    public boolean IsValid() {
        return false;
    }

    public boolean Contains(B2AABB other) {
        return false;
    }
}
