/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2BodyMoveEvent extends NativeObject {

    static public final B2BodyMoveEvent NULL = B2BodyMoveEvent.native_new();

    public B2BodyMoveEvent() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2BodyMoveEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2BodyMoveEvent native_new() {
        return new B2BodyMoveEvent((byte) 0, (char) 0);
    }

    public long GetBodyId() {
        return 0;
    }

    public B2Transform GetTransform() {
        return null;
    }

    public boolean GetFellAsleep() {
        return false;
    }
}
