/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Capsule extends NativeObject {

    static public final B2Capsule NULL = B2Capsule.native_new();

    public B2Capsule() {
    }

    public B2Capsule(B2Vec2 center1, B2Vec2 center2, float radius) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Capsule(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Capsule native_new() {
        return new B2Capsule((byte) 0, (char) 0);
    }

    public B2Vec2 GetCenter1() {
        return null;
    }

    public void SetCenter1(B2Vec2 center) {
    }

    public B2Vec2 GetCenter2() {
        return null;
    }

    public void SetCenter2(B2Vec2 center) {
    }

    public float GetRadius() {
        return 0;
    }

    public void SetRadius(float radius) {
    }
}
