/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2ChainSegment extends NativeObject {

    static public final B2ChainSegment NULL = B2ChainSegment.native_new();

    public B2ChainSegment() {
    }

    public B2ChainSegment(B2Vec2 ghost1, B2Segment segment, B2Vec2 ghost2) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ChainSegment(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ChainSegment native_new() {
        return new B2ChainSegment((byte) 0, (char) 0);
    }

    public B2Vec2 GetGhost1() {
        return null;
    }

    public void SetGhost1(B2Vec2 point) {
    }

    public B2Segment GetSegment() {
        return null;
    }

    public void SetSegment(B2Segment segment) {
    }

    public B2Vec2 GetGhost2() {
        return null;
    }

    public void SetGhost2(B2Vec2 point) {
    }
}
