/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Circle extends NativeObject {

    static public final B2Circle NULL = B2Circle.native_new();

    public B2Circle() {
    }

    public B2Circle(B2Vec2 center, float radius) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Circle(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Circle native_new() {
        return new B2Circle((byte) 0, (char) 0);
    }

    public B2Vec2 GetCenter() {
        return null;
    }

    public void SetCenter(B2Vec2 center) {
    }

    public float GetRadius() {
        return 0;
    }

    public void SetRadius(float radius) {
    }
}
