/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2DebugPolygon extends NativeObject {

    static public final B2DebugPolygon NULL = B2DebugPolygon.native_new();

    public B2DebugPolygon() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DebugPolygon(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DebugPolygon native_new() {
        return new B2DebugPolygon((byte) 0, (char) 0);
    }

    public int GetVertexCount() {
        return 0;
    }

    public B2Vec2 GetVertex(int index) {
        return null;
    }
}
