/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2DistanceOutput extends NativeObject {

    static public final B2DistanceOutput NULL = B2DistanceOutput.native_new();

    public B2DistanceOutput() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DistanceOutput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DistanceOutput native_new() {
        return new B2DistanceOutput((byte) 0, (char) 0);
    }

    public B2Vec2 GetPointA() {
        return null;
    }

    public B2Vec2 GetPointB() {
        return null;
    }

    public B2Vec2 GetNormal() {
        return null;
    }

    public float GetDistance() {
        return 0;
    }

    public int GetIterations() {
        return 0;
    }

    public int GetSimplexCount() {
        return 0;
    }
}
