/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2DistanceJointDef extends NativeObject {

    static public final B2DistanceJointDef NULL = B2DistanceJointDef.native_new();

    public B2DistanceJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2DistanceJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2DistanceJointDef native_new() {
        return new B2DistanceJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B2Vec2 GetLocalAnchorA() {
        return null;
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
    }

    public B2Vec2 GetLocalAnchorB() {
        return null;
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
    }

    public float GetLength() {
        return 0;
    }

    public void SetLength(float length) {
    }

    public boolean GetEnableSpring() {
        return false;
    }

    public void SetEnableSpring(boolean enabled) {
    }

    public float GetHertz() {
        return 0;
    }

    public void SetHertz(float hertz) {
    }

    public float GetDampingRatio() {
        return 0;
    }

    public void SetDampingRatio(float ratio) {
    }

    public boolean GetEnableLimit() {
        return false;
    }

    public void SetEnableLimit(boolean enabled) {
    }

    public float GetMinLength() {
        return 0;
    }

    public void SetMinLength(float length) {
    }

    public float GetMaxLength() {
        return 0;
    }

    public void SetMaxLength(float length) {
    }

    public boolean GetEnableMotor() {
        return false;
    }

    public void SetEnableMotor(boolean enabled) {
    }

    public float GetMaxMotorForce() {
        return 0;
    }

    public void SetMaxMotorForce(float force) {
    }

    public float GetMotorSpeed() {
        return 0;
    }

    public void SetMotorSpeed(float speed) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }
}
