/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Hull extends NativeObject {

    static public final B2Hull NULL = B2Hull.native_new();

    public B2Hull() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Hull(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Hull native_new() {
        return new B2Hull((byte) 0, (char) 0);
    }

    public void ClearPoints() {
    }

    public void AddPoint(B2Vec2 point) {
    }

    public int GetInputPointCount() {
        return 0;
    }

    public boolean Compute() {
        return false;
    }

    public boolean IsValid() {
        return false;
    }

    public int GetPointCount() {
        return 0;
    }

    public B2Vec2 GetPoint(int index) {
        return null;
    }
}
