/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2MassData extends NativeObject {

    static public final B2MassData NULL = B2MassData.native_new();

    public B2MassData() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2MassData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2MassData native_new() {
        return new B2MassData((byte) 0, (char) 0);
    }

    public float GetMass() {
        return 0;
    }

    public void SetMass(float mass) {
    }

    public B2Vec2 GetCenter() {
        return null;
    }

    public void SetCenter(B2Vec2 center) {
    }

    public float GetRotationalInertia() {
        return 0;
    }

    public void SetRotationalInertia(float inertia) {
    }
}
