/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2QueryFilter extends NativeObject {

    static public final B2QueryFilter NULL = B2QueryFilter.native_new();

    public B2QueryFilter() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2QueryFilter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2QueryFilter native_new() {
        return new B2QueryFilter((byte) 0, (char) 0);
    }

    public long GetCategoryBits() {
        return 0;
    }

    public void SetCategoryBits(long categoryBits) {
    }

    public long GetMaskBits() {
        return 0;
    }

    public void SetMaskBits(long maskBits) {
    }
}
