/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SensorBeginTouchEvent extends NativeObject {

    static public final B2SensorBeginTouchEvent NULL = B2SensorBeginTouchEvent.native_new();

    public B2SensorBeginTouchEvent() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SensorBeginTouchEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SensorBeginTouchEvent native_new() {
        return new B2SensorBeginTouchEvent((byte) 0, (char) 0);
    }

    public long GetSensorShapeId() {
        return 0;
    }

    public long GetVisitorShapeId() {
        return 0;
    }
}
