/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2ShapeProxy extends NativeObject {

    static public final B2ShapeProxy NULL = B2ShapeProxy.native_new();

    public B2ShapeProxy() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2ShapeProxy(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2ShapeProxy native_new() {
        return new B2ShapeProxy((byte) 0, (char) 0);
    }

    public void Clear() {
    }

    public void AddPoint(B2Vec2 point) {
    }

    public int GetPointCount() {
        return 0;
    }

    public B2Vec2 GetPoint(int index) {
        return null;
    }

    public float GetRadius() {
        return 0;
    }

    public void SetRadius(float radius) {
    }

    public void SetCircle(B2Circle circle) {
    }

    public void SetCapsule(B2Capsule capsule) {
    }

    public void SetSegment(B2Segment segment) {
    }

    public void SetPolygon(B2Polygon polygon) {
    }
}
