/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2SimplexCache extends NativeObject {

    static public final B2SimplexCache NULL = B2SimplexCache.native_new();

    public B2SimplexCache() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2SimplexCache(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2SimplexCache native_new() {
        return new B2SimplexCache((byte) 0, (char) 0);
    }

    public void Clear() {
    }

    public int GetCount() {
        return 0;
    }
}
