/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Sweep extends NativeObject {

    static public final B2Sweep NULL = B2Sweep.native_new();

    public B2Sweep() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Sweep(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Sweep native_new() {
        return new B2Sweep((byte) 0, (char) 0);
    }

    public B2Vec2 GetLocalCenter() {
        return null;
    }

    public void SetLocalCenter(B2Vec2 center) {
    }

    public B2Vec2 GetCenter1() {
        return null;
    }

    public void SetCenter1(B2Vec2 center) {
    }

    public B2Vec2 GetCenter2() {
        return null;
    }

    public void SetCenter2(B2Vec2 center) {
    }

    public B2Rot GetRotation1() {
        return null;
    }

    public void SetRotation1(B2Rot rotation) {
    }

    public B2Rot GetRotation2() {
        return null;
    }

    public void SetRotation2(B2Rot rotation) {
    }
}
