/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Transform extends NativeObject {

    static public final B2Transform NULL = B2Transform.native_new();

    public B2Transform() {
    }

    public B2Transform(B2Vec2 position, B2Rot rotation) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Transform(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Transform native_new() {
        return new B2Transform((byte) 0, (char) 0);
    }

    public B2Vec2 GetPosition() {
        return null;
    }

    public void SetPosition(B2Vec2 position) {
    }

    public B2Rot GetRotation() {
        return null;
    }

    public void SetRotation(B2Rot rotation) {
    }

    public B2Vec2 TransformPoint(B2Vec2 point) {
        return null;
    }

    public B2Vec2 InverseTransformPoint(B2Vec2 point) {
        return null;
    }
}
