/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2Vec2 extends NativeObject {

    static public final B2Vec2 NULL = B2Vec2.native_new();

    public B2Vec2() {
    }

    public B2Vec2(float x, float y) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2Vec2(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2Vec2 native_new() {
        return new B2Vec2((byte) 0, (char) 0);
    }

    public float GetX() {
        return 0;
    }

    public float GetY() {
        return 0;
    }

    public void SetX(float x) {
    }

    public void SetY(float y) {
    }

    public void Set(float x, float y) {
    }

    public void SetZero() {
    }

    public float Length() {
        return 0;
    }

    public float LengthSquared() {
        return 0;
    }

    public float Normalize() {
        return 0;
    }

    public boolean IsValid() {
        return false;
    }
}
