/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2WeldJointDef extends NativeObject {

    static public final B2WeldJointDef NULL = B2WeldJointDef.native_new();

    public B2WeldJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2WeldJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2WeldJointDef native_new() {
        return new B2WeldJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B2Vec2 GetLocalAnchorA() {
        return null;
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
    }

    public B2Vec2 GetLocalAnchorB() {
        return null;
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
    }

    public float GetReferenceAngle() {
        return 0;
    }

    public void SetReferenceAngle(float angle) {
    }

    public float GetLinearHertz() {
        return 0;
    }

    public void SetLinearHertz(float hertz) {
    }

    public float GetAngularHertz() {
        return 0;
    }

    public void SetAngularHertz(float hertz) {
    }

    public float GetLinearDampingRatio() {
        return 0;
    }

    public void SetLinearDampingRatio(float ratio) {
    }

    public float GetAngularDampingRatio() {
        return 0;
    }

    public void SetAngularDampingRatio(float ratio) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }
}
