/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2WheelJointDef extends NativeObject {

    static public final B2WheelJointDef NULL = B2WheelJointDef.native_new();

    public B2WheelJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2WheelJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2WheelJointDef native_new() {
        return new B2WheelJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B2Vec2 GetLocalAnchorA() {
        return null;
    }

    public void SetLocalAnchorA(B2Vec2 anchor) {
    }

    public B2Vec2 GetLocalAnchorB() {
        return null;
    }

    public void SetLocalAnchorB(B2Vec2 anchor) {
    }

    public B2Vec2 GetLocalAxisA() {
        return null;
    }

    public void SetLocalAxisA(B2Vec2 axis) {
    }

    public boolean GetEnableSpring() {
        return false;
    }

    public void SetEnableSpring(boolean enabled) {
    }

    public float GetHertz() {
        return 0;
    }

    public void SetHertz(float hertz) {
    }

    public float GetDampingRatio() {
        return 0;
    }

    public void SetDampingRatio(float ratio) {
    }

    public boolean GetEnableLimit() {
        return false;
    }

    public void SetEnableLimit(boolean enabled) {
    }

    public float GetLowerTranslation() {
        return 0;
    }

    public void SetLowerTranslation(float translation) {
    }

    public float GetUpperTranslation() {
        return 0;
    }

    public void SetUpperTranslation(float translation) {
    }

    public boolean GetEnableMotor() {
        return false;
    }

    public void SetEnableMotor(boolean enabled) {
    }

    public float GetMaxMotorTorque() {
        return 0;
    }

    public void SetMaxMotorTorque(float torque) {
    }

    public float GetMotorSpeed() {
        return 0;
    }

    public void SetMotorSpeed(float speed) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }
}
