/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B2WorldCastResult extends NativeObject {

    static public final B2WorldCastResult NULL = B2WorldCastResult.native_new();

    public B2WorldCastResult() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B2WorldCastResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B2WorldCastResult native_new() {
        return new B2WorldCastResult((byte) 0, (char) 0);
    }

    public int GetHitCount() {
        return 0;
    }

    public B2WorldCastHit GetHit(int index) {
        return null;
    }

    public int GetNodeVisits() {
        return 0;
    }

    public int GetLeafVisits() {
        return 0;
    }
}
