/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2WorldDef {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetGravity_addr(long this_addr);

    public static native void internal_native_SetGravity(long this_addr, long gravity_addr);

    public static native float internal_native_GetRestitutionThreshold(long this_addr);

    public static native void internal_native_SetRestitutionThreshold(long this_addr, float threshold);

    public static native float internal_native_GetHitEventThreshold(long this_addr);

    public static native void internal_native_SetHitEventThreshold(long this_addr, float threshold);

    public static native float internal_native_GetContactHertz(long this_addr);

    public static native void internal_native_SetContactHertz(long this_addr, float hertz);

    public static native float internal_native_GetContactDampingRatio(long this_addr);

    public static native void internal_native_SetContactDampingRatio(long this_addr, float ratio);

    public static native float internal_native_GetMaxContactPushSpeed(long this_addr);

    public static native void internal_native_SetMaxContactPushSpeed(long this_addr, float speed);

    public static native float internal_native_GetMaximumLinearSpeed(long this_addr);

    public static native void internal_native_SetMaximumLinearSpeed(long this_addr, float speed);

    public static native boolean internal_native_GetEnableSleep(long this_addr);

    public static native void internal_native_SetEnableSleep(long this_addr, boolean enabled);

    public static native boolean internal_native_GetEnableContinuous(long this_addr);

    public static native void internal_native_SetEnableContinuous(long this_addr, boolean enabled);
}
