/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2Manifold {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetNormal_addr(long this_addr);

    public static native float internal_native_GetRollingImpulse(long this_addr);

    public static native int internal_native_GetPointCount(long this_addr);

    public static native long internal_native_GetPoint_addr(long this_addr, int index);
}
