/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2DistanceJointDef {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetBodyIdA(long this_addr);

    public static native void internal_native_SetBodyIdA(long this_addr, long bodyId);

    public static native long internal_native_GetBodyIdB(long this_addr);

    public static native void internal_native_SetBodyIdB(long this_addr, long bodyId);

    public static native long internal_native_GetLocalAnchorA_addr(long this_addr);

    public static native void internal_native_SetLocalAnchorA(long this_addr, long anchor_addr);

    public static native long internal_native_GetLocalAnchorB_addr(long this_addr);

    public static native void internal_native_SetLocalAnchorB(long this_addr, long anchor_addr);

    public static native float internal_native_GetLength(long this_addr);

    public static native void internal_native_SetLength(long this_addr, float length);

    public static native boolean internal_native_GetEnableSpring(long this_addr);

    public static native void internal_native_SetEnableSpring(long this_addr, boolean enabled);

    public static native float internal_native_GetHertz(long this_addr);

    public static native void internal_native_SetHertz(long this_addr, float hertz);

    public static native float internal_native_GetDampingRatio(long this_addr);

    public static native void internal_native_SetDampingRatio(long this_addr, float ratio);

    public static native boolean internal_native_GetEnableLimit(long this_addr);

    public static native void internal_native_SetEnableLimit(long this_addr, boolean enabled);

    public static native float internal_native_GetMinLength(long this_addr);

    public static native void internal_native_SetMinLength(long this_addr, float length);

    public static native float internal_native_GetMaxLength(long this_addr);

    public static native void internal_native_SetMaxLength(long this_addr, float length);

    public static native boolean internal_native_GetEnableMotor(long this_addr);

    public static native void internal_native_SetEnableMotor(long this_addr, boolean enabled);

    public static native float internal_native_GetMaxMotorForce(long this_addr);

    public static native void internal_native_SetMaxMotorForce(long this_addr, float force);

    public static native float internal_native_GetMotorSpeed(long this_addr);

    public static native void internal_native_SetMotorSpeed(long this_addr, float speed);

    public static native boolean internal_native_GetCollideConnected(long this_addr);

    public static native void internal_native_SetCollideConnected(long this_addr, boolean collide);
}
