/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2MouseJointDef {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetBodyIdA(long this_addr);

    public static native void internal_native_SetBodyIdA(long this_addr, long bodyId);

    public static native long internal_native_GetBodyIdB(long this_addr);

    public static native void internal_native_SetBodyIdB(long this_addr, long bodyId);

    public static native long internal_native_GetTarget_addr(long this_addr);

    public static native void internal_native_SetTarget(long this_addr, long target_addr);

    public static native float internal_native_GetHertz(long this_addr);

    public static native void internal_native_SetHertz(long this_addr, float hertz);

    public static native float internal_native_GetDampingRatio(long this_addr);

    public static native void internal_native_SetDampingRatio(long this_addr, float ratio);

    public static native float internal_native_GetMaxForce(long this_addr);

    public static native void internal_native_SetMaxForce(long this_addr, float force);

    public static native boolean internal_native_GetCollideConnected(long this_addr);

    public static native void internal_native_SetCollideConnected(long this_addr, boolean collide);
}
