/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2ChainSegment {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B2Vec2_B2Segment_B2Vec2_addr(long ghost1_addr, long segment_addr, long ghost2_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetGhost1_addr(long this_addr);

    public static native void internal_native_SetGhost1(long this_addr, long point_addr);

    public static native long internal_native_GetSegment_addr(long this_addr);

    public static native void internal_native_SetSegment(long this_addr, long segment_addr);

    public static native long internal_native_GetGhost2_addr(long this_addr);

    public static native void internal_native_SetGhost2(long this_addr, long point_addr);
}
