/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2WorldOverlapResult {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_GetShapeCount(long this_addr);

    public static native long internal_native_GetShapeId(long this_addr, int index);

    public static native int internal_native_GetNodeVisits(long this_addr);

    public static native int internal_native_GetLeafVisits(long this_addr);
}
