/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2MotorJointDef {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetBodyIdA(long this_addr);

    public static native void internal_native_SetBodyIdA(long this_addr, long bodyId);

    public static native long internal_native_GetBodyIdB(long this_addr);

    public static native void internal_native_SetBodyIdB(long this_addr, long bodyId);

    public static native long internal_native_GetLinearOffset_addr(long this_addr);

    public static native void internal_native_SetLinearOffset(long this_addr, long offset_addr);

    public static native float internal_native_GetAngularOffset(long this_addr);

    public static native void internal_native_SetAngularOffset(long this_addr, float offset);

    public static native float internal_native_GetMaxForce(long this_addr);

    public static native void internal_native_SetMaxForce(long this_addr, float force);

    public static native float internal_native_GetMaxTorque(long this_addr);

    public static native void internal_native_SetMaxTorque(long this_addr, float torque);

    public static native float internal_native_GetCorrectionFactor(long this_addr);

    public static native void internal_native_SetCorrectionFactor(long this_addr, float factor);

    public static native boolean internal_native_GetCollideConnected(long this_addr);

    public static native void internal_native_SetCollideConnected(long this_addr, boolean collide);
}
