/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2ChainDef {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_ClearPoints(long this_addr);

    public static native void internal_native_AddPoint(long this_addr, long point_addr);

    public static native int internal_native_GetPointCount(long this_addr);

    public static native long internal_native_GetPoint_addr(long this_addr, int index);

    public static native void internal_native_ClearMaterials(long this_addr);

    public static native void internal_native_AddMaterial(long this_addr, long material_addr);

    public static native int internal_native_GetMaterialCount(long this_addr);

    public static native long internal_native_GetMaterial_addr(long this_addr, int index);

    public static native long internal_native_GetFilter_addr(long this_addr);

    public static native void internal_native_SetFilter(long this_addr, long filter_addr);

    public static native boolean internal_native_GetIsLoop(long this_addr);

    public static native void internal_native_SetIsLoop(long this_addr, boolean loop);

    public static native boolean internal_native_GetEnableSensorEvents(long this_addr);

    public static native void internal_native_SetEnableSensorEvents(long this_addr, boolean enabled);
}
