/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2Sweep {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetLocalCenter_addr(long this_addr);

    public static native void internal_native_SetLocalCenter(long this_addr, long center_addr);

    public static native long internal_native_GetCenter1_addr(long this_addr);

    public static native void internal_native_SetCenter1(long this_addr, long center_addr);

    public static native long internal_native_GetCenter2_addr(long this_addr);

    public static native void internal_native_SetCenter2(long this_addr, long center_addr);

    public static native long internal_native_GetRotation1_addr(long this_addr);

    public static native void internal_native_SetRotation1(long this_addr, long rotation_addr);

    public static native long internal_native_GetRotation2_addr(long this_addr);

    public static native void internal_native_SetRotation2(long this_addr, long rotation_addr);
}
