/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2AABB {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B2Vec2_B2Vec2_addr(long lowerBound_addr, long upperBound_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetLowerBound_addr(long this_addr);

    public static native void internal_native_SetLowerBound(long this_addr, long lowerBound_addr);

    public static native long internal_native_GetUpperBound_addr(long this_addr);

    public static native void internal_native_SetUpperBound(long this_addr, long upperBound_addr);

    public static native long internal_native_GetCenter_addr(long this_addr);

    public static native long internal_native_GetExtents_addr(long this_addr);

    public static native float internal_native_GetPerimeter(long this_addr);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native boolean internal_native_Contains(long this_addr, long other_addr);
}
