/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2Circle {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B2Vec2_float_addr(long center_addr, float radius);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetCenter_addr(long this_addr);

    public static native void internal_native_SetCenter(long this_addr, long center_addr);

    public static native float internal_native_GetRadius(long this_addr);

    public static native void internal_native_SetRadius(long this_addr, float radius);
}
