/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2Rot {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_float_addr(float radians);

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_GetCosine(long this_addr);

    public static native float internal_native_GetSine(long this_addr);

    public static native float internal_native_GetAngle(long this_addr);

    public static native void internal_native_Set(long this_addr, float radians);

    public static native void internal_native_SetIdentity(long this_addr);

    public static native long internal_native_RotateVector_addr(long this_addr, long vector_addr);

    public static native long internal_native_InverseRotateVector_addr(long this_addr, long vector_addr);
}
