/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2TOIInput {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetProxyA_addr(long this_addr);

    public static native void internal_native_SetProxyA(long this_addr, long proxy_addr);

    public static native long internal_native_GetProxyB_addr(long this_addr);

    public static native void internal_native_SetProxyB(long this_addr, long proxy_addr);

    public static native long internal_native_GetSweepA_addr(long this_addr);

    public static native void internal_native_SetSweepA(long this_addr, long sweep_addr);

    public static native long internal_native_GetSweepB_addr(long this_addr);

    public static native void internal_native_SetSweepB(long this_addr, long sweep_addr);

    public static native float internal_native_GetMaxFraction(long this_addr);

    public static native void internal_native_SetMaxFraction(long this_addr, float fraction);
}
