/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box2d.natives;

import com.github.xpenatan.box2d.*;

final public class JNI_B2Segment {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B2Vec2_B2Vec2_addr(long point1_addr, long point2_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetPoint1_addr(long this_addr);

    public static native void internal_native_SetPoint1(long this_addr, long point_addr);

    public static native long internal_native_GetPoint2_addr(long this_addr);

    public static native void internal_native_SetPoint2(long this_addr, long point_addr);
}
